.github/workflows/ci.yml

- CI Pipline: lint, unit test, e2e test, set code coverage

[Feature] CI Pipeline을 구축하라

---

.husky/pre-commit
package.json
yarn.lock

- 변경된 파일만 pre commit해주게 하는 lint-staged를 적용

[Setting] pre commit의 lint-staged를 적용하라

---

cypress/integration/sample/sample.spec.ts
firestore.rules
fixtures/profile.ts
src/components/SignInOAuthButtons.test.tsx
src/components/SignInOAuthButtons.tsx
src/containers/HomeContainer.test.tsx
src/containers/HomeContainer.tsx
src/containers/RegisterContainer.test.tsx
src/containers/RegisterContainer.tsx
src/containers/SignInContainer.test.tsx
src/containers/SignInContainer.tsx
src/models/auth.ts
src/pages/_app.tsx
src/pages/register.tsx
src/reducers/authSlice.test.ts
src/reducers/authSlice.ts
src/reducers/rootReducer.test.ts
src/services/api/__mocks__/auth.ts
src/services/api/auth.test.ts
src/services/api/auth.ts
src/services/firebase.ts
src/utils/utils.test.ts
src/utils/utils.ts

- 추가적인(닉네임(id), 포트폴리오 url, 프로필 사진) User Profile 정보가 입력되지 않았으면, register 페이지로 이동
- firebase firestore 룰 변경

[Feature] 로그인 후 추가적인 가입정보를 입력하지 않았으면 register 페이지로 redirect된다.

---

.eslintrc.js
package.json
src/components/RegisterForm.test.tsx
src/components/RegisterForm.tsx
src/containers/RegisterContainer.test.tsx
src/containers/RegisterContainer.tsx
src/models/auth.ts
src/utils/utils.test.ts
src/utils/utils.ts
yarn.lock

- Install dependency react-hook-form, @hookform/resolvers, yup
- 이름, 이메일(고정), 포트폴리오 URL(option), 아이디 form
- 이름 빈칸일 때: "이름을 입력해주세요."
- 아이디 빈칸일 때: "아이디를 입력해주세요."

[Feature] 로그인 후 기본 회원 정보를 등록하는 Form을 구현하라

---

package.json
src/components/Header.test.tsx
src/components/Header.tsx
src/containers/HeaderContainer.test.tsx
src/containers/HeaderContainer.tsx
src/containers/HomeContainer.tsx
src/containers/RegisterContainer.test.tsx
src/containers/RegisterContainer.tsx
src/containers/SignInContainer.test.tsx
src/containers/SignInContainer.tsx
src/reducers/authSlice.test.ts
src/reducers/authSlice.ts
src/services/api/__mocks__/auth.ts
src/services/api/auth.test.ts
src/services/api/auth.ts
yarn.lock

- 정보입력하면 계정 생성
- 정상적으로 생성 후 홈 화면으로 이동
- Install react-use dependency

[Feature] OAuth 로그인 후 닉네임, 포트폴리오 URL 정보입력 후 계정을 생성하게 하라

---

src/components/Header.test.tsx
src/components/Header.tsx
src/containers/HeaderContainer.test.tsx
src/containers/HeaderContainer.tsx
src/pages/_app.tsx
src/reducers/authSlice.test.ts
src/reducers/authSlice.ts
src/services/api/__mocks__/auth.ts
src/services/api/auth.test.ts
src/services/api/auth.ts

- 로그아웃 기능 구현
- 사용자가 로그인 중일 때 로그아웃 버튼 클릭시 로그아웃

[Feature] 사용자가 로그아웃을 할 수 있게 하라

---

src/components/common/Header.test.tsx
src/components/common/Header.tsx
src/pages/api/auth/[...nextauth].ts
types/environment.d.ts

[Feature] 카카오 OAuth 적용하라

---

babel.config.js
package.json
src/pages/_app.tsx
src/styles/GlobalStyles.tsx
yarn.lock

- CSS in JS를 사용하기 위해 emotion 사용
- Install dependencies @emotion/react, @emotion/styled emotion-normalize
- Install dev dependency @emotion/babel-plugin
- Global style을 nomalize css로 적용
- next.js emotion을 위한 babel 세팅

[Feature] emotion 초기 세팅을 하라

---

fixtures/profile.ts
src/components/auth/SignUpForm.tsx
src/components/common/Header.tsx
src/containers/auth/SignUpContainer.test.tsx
src/containers/auth/SignUpContainer.tsx
src/models/auth.ts
src/pages/api/auth/[...nextauth].ts
src/pages/index.tsx
src/pages/signup.tsx
src/reducers/store.ts
src/services/api/auth.test.ts
src/services/api/auth.ts
types/next-auth.d.ts

- 서버사이드에서 session 정보를 가져온다.
- 서버사이드에서 redux store에 넣는다.
- 이미 signup된 계정이 가입페이지로 다시 이동했을 때 히든 케이스 추가

[Fix] 세션 정보를 가져올 때 한박자 늦게 보여지는 문제 해결하라

---

.eslintrc.js
package.json
src/components/auth/SignInModal.test.tsx
src/components/auth/SignInModal.tsx
src/components/auth/SocialButtonGroup.test.tsx
src/components/auth/SocialButtonGroup.tsx
src/components/common/Header.test.tsx
src/components/common/Header.tsx
src/containers/auth/SignInModalContainer.test.tsx
src/containers/auth/SignInModalContainer.tsx
src/containers/common/HeaderContainer.test.tsx
src/styles/transitions.ts
src/styles/zIndexes.ts
yarn.lock

- Install dependency @emotion/eslint-plugin
- 모달창 구현
- 기존에 홈화면에 있던 OAuth 버튼을 모달창에 소셜 로그인 버튼으로 변경

[Feature] 로그인 모달창을 구현하라

---

.eslintrc.js
cypress/integration/sample/sample.spec.ts
src/components/auth/SignInModal.tsx
src/components/auth/SocialButtonGroup.tsx
src/components/common/Header.test.tsx
src/components/common/Header.tsx
src/components/new/NewHeader.test.tsx
src/components/new/NewHeader.tsx
src/components/new/NewWriteForm.test.tsx
src/components/new/NewWriteForm.tsx
src/containers/Home/HomeContainer.test.tsx
src/containers/Home/HomeContainer.tsx
src/containers/auth/SignInModalContainer.tsx
src/containers/new/NewHeaderContainer.test.tsx
src/containers/new/NewHeaderContainer.tsx
src/containers/new/NewWriteFormContainer.test.tsx
src/containers/new/NewWriteFormContainer.tsx
src/pages/new.tsx

- 세션이 존재하는 사용자는 팀 모집하기 작성 페이지로 이동한다.
- next link로 인한 eslint rule 추가

[Feature] 로그인한 사용자가 "팀 모집하기" 페이지로 이동할 수 있게 하라

---

fixtures/writeFields.ts
src/components/new/NewHeader.test.tsx
src/components/new/NewHeader.tsx
src/components/new/NewWriteForm.test.tsx
src/components/new/NewWriteForm.tsx
src/containers/new/NewHeaderContainer.test.tsx
src/containers/new/NewHeaderContainer.tsx
src/containers/new/NewWriteFormContainer.test.tsx
src/containers/new/NewWriteFormContainer.tsx
src/models/group.ts
src/reducers/authSlice.test.ts
src/reducers/authSlice.ts
src/reducers/groupSlice.test.ts
src/reducers/groupSlice.ts
src/reducers/rootReducer.test.ts
src/reducers/rootReducer.ts
src/services/api/__mocks__/group.ts
src/services/api/auth.test.ts
src/services/api/auth.ts
src/services/api/group.test.ts
src/services/api/group.ts
src/services/firebase.ts
src/utils/utils.test.ts
src/utils/utils.ts

- 제목과 내용을 입력 후 등록하기 버튼을 누르면 글이 등록된다.
- 현재 등록 후엔 메인 페이지로 이동. (추후 해당 작성 글 페이지로 이동시키기)

[Feature] 팀 모집하기 글을 등록할 수 있게 하라

---

__mocks__/next-auth/client.js
src/pages/index.test.tsx
src/pages/new.test.tsx
src/pages/signup.test.tsx

- index, signup, new 페이지 테스트 코드 작성

[Refactor] 기존에 작성하지 못했던 pages 테스트 코드를 작성하라

---

src/components/common/Header.test.tsx
src/components/common/Header.tsx
src/containers/auth/SignInModalContainer.test.tsx
src/containers/auth/SignInModalContainer.tsx
src/containers/common/HeaderContainer.test.tsx
src/containers/common/HeaderContainer.tsx
src/pages/_app.page.tsx
src/pages/index.test.tsx
src/pages/signup.test.tsx
src/reducers/authSlice.test.ts
src/reducers/authSlice.ts

- 추후 해당 모달창이 필요에 의해서 모든 페이지에서 보이게할 필요가 있음.

[Refacotor] Sign In 모달창의 상태를 전역으로 변경하라

---

.eslintrc.js
fixtures/profile.ts
src/components/auth/SignUpForm.test.tsx
src/components/auth/SignUpForm.tsx
src/components/common/Select.test.tsx
src/components/common/Select.tsx
src/containers/auth/SignUpContainer.test.tsx
src/models/auth.ts
src/services/api/auth.test.ts
src/services/api/auth.ts

- 포지션 항목 (학생, 프론트, 백엔드, 디자인, 직접 입력)

[Feature] Sign Up 페이지에서 포지션을 선택할 수 있게하라

---

fixtures/initialStore.ts
src/components/auth/SignInModal.test.tsx
src/components/new/RegisterModal.test.tsx
src/components/new/RegisterModal.tsx
src/components/new/RegisterModalForm.test.tsx
src/components/new/RegisterModalForm.tsx
src/containers/new/NewHeaderContainer.test.tsx
src/containers/new/NewHeaderContainer.tsx
src/containers/new/RegisterModalContainer.test.tsx
src/containers/new/RegisterModalContainer.tsx
src/pages/index.test.tsx
src/pages/new.page.tsx
src/pages/signup.test.tsx
src/reducers/groupSlice.test.ts
src/reducers/groupSlice.ts
src/reducers/rootReducer.test.ts
src/styles/zIndexes.ts

- 글작성 후 등록하기 버튼 클릭시 모달창이 나타난다
- 모달창 닫기 버튼 클릭 하면 모달창이 닫힌다.
- 모달창 등록하기 버튼을 클릭하면 닫히고 메인 페이지로 이동한다

[Feature] 등록하기 모달창 뷰 페이지를 구현하라

---

fixtures/group.ts
fixtures/initialStore.ts
src/components/detail/DetailHeaderSection.test.tsx
src/components/detail/DetailHeaderSection.tsx
src/containers/detail/DetailHeaderContainer.test.tsx
src/containers/detail/DetailHeaderContainer.tsx
src/models/group.ts
src/pages/detail/[id].page.tsx
src/pages/detail/[id].test.tsx
src/reducers/groupSlice.test.ts
src/reducers/groupSlice.ts
src/services/api/__mocks__/auth.ts
src/services/api/auth.test.ts
src/services/api/auth.ts

- 작성자 프로필이 간단히 보인다. (프로필 사진과 닉네임 || 이메일)

[Feature] 디테일 페이지에서 작성자 정보를 볼 수 있게하라

---

firestore.indexes.json
src/components/home/FilterBar.test.tsx
src/components/home/FilterBar.tsx
src/containers/home/FilterBarContainer.test.tsx
src/containers/home/FilterBarContainer.tsx
src/containers/home/RecruitPostsContainer.tsx
src/pages/index.page.tsx
src/reducers/groupSlice.test.ts
src/reducers/groupSlice.ts
src/services/api/group.test.ts
src/services/api/group.ts

- 스터디, 프로젝트 종류에 따라서 필터링된 리스트를 볼 수 있다.
- 전체인 경우는 모든 카테고리 리스트가 보인다.

[Feature] 홈페이지의 스터디(프로젝트) 리스트를 필터링할 수 있게하라

---

src/components/home/RecruitPost.test.tsx
src/components/home/RecruitPost.tsx

- 모집 글의 작성자 닉네임과 프로필 사진을 볼 수 있다

[Feature] 홈페이지의 각 모집글마다의 작성자 정보를 볼 수 있게하라

---

fixtures/initialStore.ts
src/components/detail/CommentForm.test.tsx
src/components/detail/CommentForm.tsx
src/containers/detail/CommentsContainer.test.tsx
src/containers/detail/CommentsContainer.tsx
src/models/group.ts
src/pages/detail/[id].page.tsx
src/pages/detail/[id].test.tsx
src/reducers/groupSlice.test.ts
src/reducers/groupSlice.ts
src/reducers/rootReducer.test.ts
src/services/api/__mocks__/comment.ts
src/services/api/comment.test.ts
src/services/api/comment.ts
src/services/api/group.test.ts
src/services/api/group.ts

[Feature] 로그인한 사용자는 각 모집글에 댓글을 입력할 수 있게하라

---

firestore.indexes.json
fixtures/comment.ts
src/components/common/ProfileImage.test.tsx
src/components/common/ProfileImage.tsx
src/components/detail/CommentForm.tsx
src/components/detail/CommentView.test.tsx
src/components/detail/CommentView.tsx
src/components/detail/CommentsView.test.tsx
src/components/detail/CommentsView.tsx
src/components/detail/DetailHeaderSection.test.tsx
src/components/detail/DetailHeaderSection.tsx
src/components/home/RecruitPost.test.tsx
src/components/home/RecruitPost.tsx
src/containers/detail/CommentsContainer.test.tsx
src/containers/detail/CommentsContainer.tsx
src/pages/detail/[id].test.tsx
src/reducers/groupSlice.test.ts
src/reducers/groupSlice.ts
src/services/api/__mocks__/comment.ts
src/services/api/comment.test.ts
src/services/api/comment.ts
src/services/api/group.test.ts
src/utils/__mocks__/firestore.ts
src/utils/firestore.test.ts
src/utils/firestore.ts
src/utils/utils.test.ts
src/utils/utils.ts

- 각 모집글에 등록된 댓글을 볼 수 있다.
- 댓글이 존재하지 않은 경우 "댓글이 존재하지 않아요!"

[Feature] 각 모집글에 등록된 댓글을 볼 수 있게 하라.

---

src/__mocks__/firebase/app.js
src/services/firebase/index.ts

- dev에서는 미적용
- production에서만 적용

[Feature] Firebase analytics를 적용하라

---

src/services/firebase/index.ts

[Fix] firebase analytics 적용안되는 문제를 수정하라

---

src/components/write/PublishModalForm.test.tsx
src/components/write/PublishModalForm.tsx
src/components/write/WriteForm.test.tsx
src/components/write/WriteForm.tsx
src/containers/write/PublishModalContainer.test.tsx
src/containers/write/WriteFormContainer.test.tsx

- 등록하기 모달창에 위치한 태그 입력 폼을 글 내용 작성 폼 밑으로 이동

[Refactor] 등록하기 모달창에 위치한 태그 입력 폼을 글 내용 작성 폼 밑으로 이동시켜라

---

fixtures/initialStore.ts
src/containers/write/PublishModalContainer.tsx
src/models/group.ts
src/reducers/groupSlice.test.ts
src/reducers/groupSlice.ts
src/reducers/rootReducer.test.ts
src/reducers/rootReducer.ts
src/services/api/__mocks__/tagsCount.ts
src/services/api/tagsCount.test.ts
src/services/api/tagsCount.ts

- 태그 Count Get API
- 태그 Count update API
- 글 작성할 때 태그에 따라서 count 수 증가 API

[Feature] 홈페이지에 나타날 태그를 나열하기 위한 api를 구현하라

---

src/components/common/DropDown.test.tsx
src/components/common/DropDown.tsx
src/components/common/Header.test.tsx
src/components/common/Header.tsx
src/components/common/UserNavbar.test.tsx
src/components/common/UserNavbar.tsx
src/containers/common/HeaderContainer.test.tsx
src/styles/GlobalStyles.tsx

[Feature] 유저 드롭다운 디자인 CSS를 개선하라

---

src/components/auth/SignInModal.tsx
src/components/common/DropDown.tsx
src/components/common/Tag.test.tsx
src/components/common/Tag.tsx
src/components/home/TagsBar.tsx
src/components/write/TagForm.test.tsx
src/components/write/TagForm.tsx
src/components/write/TagList.test.tsx
src/components/write/TagList.tsx

- Tag 작성할 때 컴포넌트와 보여지는 Tag 컴포넌트 구현

[Feature] Tag 공통 컴포넌트 CSS 적용하기를 적용하라

---

src/components/detail/DetailContentsSection.tsx

[Feature] 누락 Tag 컴포넌트 CSS를 적용하라

---

package.json
yarn.lock

- Downgrade firebase v.9.4 to v.9.1
- https://github.com/vercel/next.js/issues/32527
- https://github.com/vercel/next.js/discussions/32582
- https://github.com/firebase/firebase-js-sdk/issues/5823

[Fix] Firebase v.9.6가 vercel prod에서 깨지는 오류를 수정하라

---

src/components/auth/SignInError.tsx
src/components/auth/SignInModal.tsx
src/components/auth/SocialButtonGroup.tsx
src/components/common/Button.test.tsx
src/components/common/Button.tsx
src/components/common/DropDown.tsx
src/components/detail/DetailHeaderSection.tsx
src/components/write/TagForm.tsx
src/styles/GlobalStyles.tsx
src/styles/fontStyles.test.ts
src/styles/fontStyles.ts

- font-size, line-height, font-weight를 공통으로 정의

[Feature] 디자인 시스템의 font style을 공통으로 정의하라

---

__mocks__/firebase/firestore.js
src/components/detail/CommentView.test.tsx
src/components/detail/CommentView.tsx
src/components/detail/CommentsView.test.tsx
src/components/detail/CommentsView.tsx
src/components/detail/DetailContentsSection.tsx
src/containers/detail/CommentsContainer.test.tsx
src/containers/detail/CommentsContainer.tsx
src/reducers/groupSlice.test.ts
src/reducers/groupSlice.ts
src/services/api/__mocks__/comment.ts
src/services/api/comment.test.ts
src/services/api/comment.ts
src/styles/GlobalStyles.tsx

[Feature] 댓글 작성자는 댓글을 삭제하도록 하라

---

src/components/common/Button.tsx
src/components/common/ConfirmModal.test.tsx
src/components/common/ConfirmModal.tsx
src/components/detail/modal/AskDeleteComment.test.tsx
src/components/detail/modal/AskDeleteComment.tsx
src/pages/text.page.tsx
src/styles/zIndexes.ts

- Confirm Modal 공통 컴포넌트 구현
- 댓글 삭제 모달 컴포넌트 추가

[Feature] Confirm Modal 공통 컴포넌트를 구현하라

---

fixtures/group.ts
src/components/detail/ApplicantStatusButton.test.tsx
src/components/detail/ApplicantStatusButton.tsx
src/components/detail/CommentForm.tsx
src/components/detail/CommentView.tsx
src/components/detail/DetailHeaderSection.test.tsx
src/components/detail/DetailHeaderSection.tsx
src/components/detail/WriterStatusButtons.test.tsx
src/components/detail/WriterStatusButtons.tsx
src/components/home/RecruitPost.tsx
src/containers/detail/DetailHeaderContainer.test.tsx
src/containers/detail/DetailHeaderContainer.tsx
src/hooks/useCurrentTime.test.ts
src/hooks/useCurrentTime.ts
src/models/group.ts
src/services/api/group.test.ts
src/services/api/group.ts
src/styles/Divider.ts

- 조회수(views), 모집 완료 상태(isCompleted) 추가
- iSCompleted 상태일 땐, useInterval 사용할 필요 없음.
- 모집 완료에 따른 버튼 상태 변화
- 디테일 페이지의 조회수 뷰 추가

[Feature] 모집 완료 상태 및 조회수 상태를 추가하라

---

src/components/common/Textarea.test.tsx
src/components/common/Textarea.tsx
src/components/detail/CommentForm.test.tsx
src/components/detail/CommentForm.tsx
src/containers/detail/CommentsContainer.test.tsx
src/containers/detail/CommentsContainer.tsx
src/styles/GlobalStyles.tsx

- focus, disable, error 상태일 때에 따른 style적용
- 댓글 textarea에 공통 컴포넌트 적용

[Feature] Textarea 공통 컴포넌트를 구현하라

---

src/components/detail/ApplicantStatusButton.test.tsx
src/components/detail/ApplicantStatusButton.tsx
src/components/detail/DetailHeaderSection.test.tsx
src/components/detail/DetailHeaderSection.tsx
src/components/detail/DetailStatusButton.test.tsx
src/components/detail/DetailStatusButton.tsx
src/containers/detail/DetailHeaderContainer.test.tsx
src/containers/detail/DetailHeaderContainer.tsx
src/reducers/groupSlice.test.ts
src/reducers/groupSlice.ts
src/services/api/__mocks__/applicants.ts
src/services/api/applicants.test.ts
src/services/api/applicants.ts

- 스터디 또는 프로젝트를 신청한 사용자는 신청을 취소할 수 있다.

[Feature] 스터디 또는 프로젝트를 신청한 사용자는 신청을 취소할 수 있게하라

---

.eslintrc.js
src/components/common/FormModal.test.tsx
src/components/common/FormModal.tsx
src/components/common/Textarea.tsx
src/components/detail/ApplyFormModal.tsx
src/styles/palette.ts

- 신청 모달 스타일 적용
- 소개글 미입력시 disabled

[Feature] 신청 모달 스타일을 적용하라

---

__mocks__/firebase-admin.js
package.json
src/components/common/Core.tsx
src/containers/auth/SignInModalContainer.tsx
src/containers/home/RecruitPostsContainer.test.tsx
src/containers/home/RecruitPostsContainer.tsx
src/pages/_app.page.tsx
src/pages/api/authenticated.api.ts
src/pages/api/authenticated.test.ts
src/pages/detail/[id]/applicants.page.tsx
src/pages/detail/[id]/applicants.test.tsx
src/pages/index.test.tsx
src/services/firebase/firebaseAdmin.test.ts
src/services/firebase/firebaseAdmin.ts
src/styles/GlobalStyles.tsx
yarn.lock

- 비로그인 사용자나 작성자가 아닌 사용자는 홈으로 redirect로 한다.
- query.error가 unauthenticated인 경우 toast.error가 나타난다.

[Feature] 신청현황 페이지는 작성자만 접근이 가능하도록 하라

---

fixtures/applicant.ts
src/components/applicants/ApplicantItem.test.tsx
src/components/applicants/ApplicantItem.tsx
src/components/applicants/ApplicationStatus.test.tsx
src/components/applicants/ApplicationStatus.tsx
src/components/applicants/Header.test.tsx
src/components/applicants/Header.tsx
src/components/common/Core.tsx
src/components/detail/ApplicantStatusButton.test.tsx
src/components/detail/DetailHeaderSection.tsx
src/components/detail/DetailStatusButton.tsx
src/components/detail/WriterStatusButtons.test.tsx
src/components/detail/WriterStatusButtons.tsx
src/containers/applicants/ApplicationStatusContainer.test.tsx
src/containers/applicants/ApplicationStatusContainer.tsx
src/containers/detail/DetailHeaderContainer.test.tsx
src/pages/detail/[id].page.tsx
src/pages/detail/[id].test.tsx
src/pages/detail/[id]/applicants.page.tsx
src/pages/detail/[id]/applicants.test.tsx
src/reducers/groupSlice.test.ts
src/services/api/applicants.test.ts
src/styles/GlobalStyles.tsx
src/styles/Layout.tsx

- 글 작성자는 신청 현황 페이지의 신청자 리스트를 볼 수 있다.
- URL: `/detail/{groupId}/applicants`

[Feature] 글 작성자는 신청 현황 페이지의 신청자 리스트를 볼 수 있게하라

---

src/components/applicants/ApplicantItem.test.tsx
src/components/applicants/ApplicantItem.tsx
src/components/applicants/ApplicationStatus.test.tsx
src/components/applicants/ApplicationStatus.tsx
src/containers/applicants/ApplicationStatusContainer.test.tsx
src/containers/applicants/ApplicationStatusContainer.tsx
src/reducers/groupSlice.test.ts
src/reducers/groupSlice.ts
src/services/api/__mocks__/applicants.ts
src/services/api/applicants.test.ts
src/services/api/applicants.ts

- 신청 현황 페이지에서 작성자는 신청자의 참여 여부를 선택 및 해제할 수 있다
- 모집완료 버튼은 1명이상 일 때부터 활성화된다.

[Feature] 작성자는 신청자의 참여 여부를 선택 및 해제할 수 있게하라

---

src/components/home/RecruitPost.tsx
src/components/home/RecruitPosts.tsx
src/styles/Divider.ts

[Feature] 카드 컴포넌트에 CSS를 적용한다.

---

src/components/applicants/ApplicantItem.tsx
src/components/applicants/CompleteApplyFormModal.tsx
src/components/common/FormModal.test.tsx
src/components/common/FormModal.tsx
src/components/detail/ApplicantStatusButton.test.tsx
src/components/detail/ApplicantStatusButton.tsx

- 모집 완료 후 비로그인 및 승인되지 않은 유저한테도 팀원보기 버튼이 보이는 오류 수정
- 신청현황의 신청자 포트폴리오 URL CSS 수정
- 모집완료 CSS 수정

[Fix] 모집 완료 후 비로그인 및 승인되지 않은 유저한테도 팀원보기 버튼이 보이는 오류를 수정하라

---

src/components/applicants/ApplicantItem.tsx
src/components/applicants/ApplicationStatusHeader.test.tsx
src/components/applicants/ApplicationStatusHeader.tsx
src/components/applicants/CompleteApplyFormModal.test.tsx
src/components/applicants/CompleteApplyFormModal.tsx
src/components/common/FormModal.tsx
src/components/detail/ApplyFormModal.tsx
src/containers/applicants/ApplicationStatusHeaderContainer.test.tsx
src/containers/applicants/ApplicationStatusHeaderContainer.tsx
src/hooks/useCurrentTime.ts
src/hooks/useRecruitDateStatus.ts
src/utils/utils.test.ts
src/utils/utils.ts

- 모집 마감시간 이전인 경우 모집 완료 모달창에서 주의 메시지 렌더링

[Feature] 모집 마감시간 이전인 경우 모집 완료 모달창에서 주의 메시지가 나타나게하라

---

.eslintrc.js
src/components/common/Input.test.tsx
src/components/common/Input.tsx
src/components/detail/ApplyFormModal.test.tsx
src/components/detail/ApplyFormModal.tsx
src/styles/GlobalStyles.tsx

- Input 공통 컴포넌트 구현
- Label, helperText, error, focus, disabled, readOnly, clear button

[Feature] Input 공통 컴포넌트 구현하라

---

src/components/detail/ApplyFormModal.tsx
src/components/detail/DetailHeaderSection.test.tsx
src/components/detail/DetailHeaderSection.tsx
src/reducers/rootReducer.test.ts
src/reducers/rootReducer.ts

- 포트폴리오 clear 버튼 클릭 후 submit 되지 않는 오류 수정
- 작성자가 모집 완료 버튼 클릭 후 디테일 페이지에서 뒤로가기시 state가 변해 댓글과 신청 현황이 안보이는 현상 수정

[Fix] 포트폴리오 clear 버튼 클릭 후 submit 되지 않는 오류를 수정하라

---

src/components/applicants/ApplicationStatus.test.tsx
src/components/applicants/ApplicationStatus.tsx
src/components/common/EmptyStateArea.test.tsx
src/components/common/EmptyStateArea.tsx
src/containers/applicants/ApplicationStatusContainer.test.tsx
src/containers/applicants/ApplicationStatusContainer.tsx

- Empty State의 공통 컴포넌트를 구현한다.
- 신청현황에 Empty State 컴포넌트를 적용한다.

[Feature] Empty State의 공통 컴포넌트를 구현

---

package.json
src/components/common/SwitchButton.test.tsx
src/components/common/SwitchButton.tsx
src/containers/home/StatusBarContainer.test.tsx
src/containers/home/StatusBarContainer.tsx
yarn.lock

- 모집 마감 안보기 switch 버튼 구현
- Install react-toggle dependency

[Feature] 모집 마감 안보기 switch 버튼을 구현하라

---

src/components/myInfo/MyInfoTab.test.tsx
src/components/myInfo/MyInfoTab.tsx
src/pages/myinfo/applied.page.tsx
src/pages/myinfo/recruited.page.tsx

- myinfo 상단의 MyInfoTab 스타일 적용
- 신청한 팀, 모집한 팀 Empty State 구현

[UI/UX] myinfo 페이지의 탭 스타일과 Empty State를 구현

---

src/containers/auth/SignInModalContainer.test.tsx
src/containers/auth/SignInModalContainer.tsx
src/containers/common/HeaderContainer.test.tsx
src/containers/common/HeaderContainer.tsx
src/containers/detail/CommentsContainer.test.tsx
src/containers/detail/CommentsContainer.tsx
src/containers/detail/DetailHeaderContainer.test.tsx
src/containers/detail/DetailHeaderContainer.tsx
src/containers/write/PublishModalContainer.test.tsx
src/containers/write/PublishModalContainer.tsx
src/containers/write/WriteHeaderContainer.test.tsx
src/containers/write/WriteHeaderContainer.tsx
src/pages/write.test.tsx
src/recoil/modal/atom.ts
src/reducers/authSlice.test.ts
src/reducers/authSlice.ts
src/reducers/groupSlice.test.ts
src/reducers/groupSlice.ts
src/test/InjectTestingRecoilState.tsx

- SignInModal과 PublishModal의 Client State를 Redux에서 Recoil로 변경

[Improve] SignInModal과 PublishModal의 Client State를 Recoil로 변경하라

---

src/containers/applicants/ApplicationStatusContainer.test.tsx
src/containers/applicants/ApplicationStatusContainer.tsx
src/containers/applicants/ApplicationStatusHeaderContainer.test.tsx
src/containers/applicants/ApplicationStatusHeaderContainer.tsx
src/hooks/api/applicant/useUpdateApplicant.test.ts
src/hooks/api/applicant/useUpdateApplicant.ts
src/hooks/api/group/useUpdateCompletedApply.test.ts
src/hooks/api/group/useUpdateCompletedApply.ts
src/pages/detail/[id]/applicants.page.tsx
src/pages/detail/[id]/applicants.test.tsx
src/reducers/groupSlice.test.ts
src/reducers/groupSlice.ts

- 신청자 선택 및 해제 API React Query 적용
- 모집 완료 API React Query 적용
- 신청 현황 보기 페이지 Redux 걷어내기

[Improve] 신청 현황 보기 페이지를 React Query를 적용하라

---

src/components/common/DropDown.tsx

[UI/UX] 유저 드롭다운 디자인 CSS를 개선하라

---

src/components/myInfo/MyGroup.tsx
src/components/myInfo/MyGroups.tsx

- 모집한 팀, 신청한 팀 리스트 컴포넌트(MyGroup)에 CSS 적용
- recruitDateStatus의 상태에 따른 CSS 적용 제외
- 썸네일 이미지 적용 제외

[UI/UX] 모집한 팀, 신청한 팀 리스트 컴포넌트에 CSS를 적용하라

---

.github/workflows/ci.yml
src/containers/auth/SignInModalContainer.test.tsx

[Fix] CodeCov Coverage broken error

[Fix] CodeCov Coverage broken error

---

package.json
src/components/auth/SignUpForm.test.tsx
src/components/auth/SignUpForm.tsx
src/components/common/CreatableSelectBox.test.tsx
src/components/common/CreatableSelectBox.tsx
src/components/common/HelperMessage.test.tsx
src/components/common/HelperMessage.tsx
src/components/common/Input.tsx
src/components/common/Label.test.tsx
src/components/common/Label.tsx
src/containers/auth/SignUpContainer.test.tsx
src/models/group.ts
src/models/index.ts
yarn.lock

- 직접 입력이 존재하는 Select 컴포넌트 구현
- Label, HelperMessage Fields와 같이 구현
- Error 상태, focus, clear, size.. 상태
- Install react-select dependency

[Feature] CreatebleSelect 공통 컴포넌트 구현하라

---

src/components/detail/DetailHeaderSection.tsx
src/components/home/RecruitPost.tsx
src/components/myInfo/MyGroup.tsx
src/components/myInfo/MyGroups.tsx
src/components/myInfo/MyInfoLayout.tsx
src/components/myInfo/MyInfoTab.test.tsx
src/components/myInfo/MyInfoTab.tsx
src/containers/myInfo/MyInfoTabContainer.test.tsx
src/containers/myInfo/MyInfoTabContainer.tsx
src/hooks/useGroupRecruitmentStatus.test.ts
src/hooks/useGroupRecruitmentStatus.ts
src/hooks/useMyInfoRecruitmentStatus.ts
src/hooks/useRecruitDateStatus.test.ts
src/hooks/useRecruitDateStatus.ts
src/models/group.ts
src/pages/myinfo/setting.page.tsx

- manualRecruiting: 수동이고 모집중일 때
- automaticRecruiting: 자동이고 모집중일 때
- automaticCloseRecruitment: 자동이고 모집 마감일 때
- manualCompletedRecruitment: 수동이고 모집 완료일 때
- automaticBeforeCompletedRecruitment: 자동이고 모집 마감 일자 이전에 모집 완료를 했을 때
- automaticAfterCompletedRecruitment: 자동이고 모집 마감 일자 이후에 모집 완료를 했을 때

[Feature] 글 모집 상태에 따른 모집 상태 정보 구현하라

---

src/components/common/SelectBox.test.tsx
src/components/common/SelectBox.tsx
src/components/home/FilterBar.test.tsx
src/components/home/FilterBar.tsx
src/containers/home/StatusBarContainer.test.tsx
src/containers/home/StatusBarContainer.tsx

[Feature] Select Box 공통 컴포넌트를 구현하라

---

src/components/myInfo/MyGroup.test.tsx
src/components/myInfo/MyGroup.tsx

- MyGroup 컴포넌트에 모집 상태에 따라 다른 메시지를 노출한다.
- MyGroup 컴포넌트에 모집 상태에 따른 CSS를 적용한다.

[Feature] MyGroup에 모집 상태를 적용하라

---

src/components/myInfo/MyInfoTab.test.tsx
src/components/myInfo/MyInfoTab.tsx
src/containers/myInfo/MyInfoTabContainer.test.tsx
src/containers/myInfo/MyInfoTabContainer.tsx

- MyInfoTab에 모집한 팀, 신청한 팀의 개수가 함께 노출되어야 한다.

[Feature] MyInfoTab에 모집한 팀, 신청한 팀의 개수를 추가하라

---

src/components/auth/SignUpForm.test.tsx
src/components/auth/SignUpForm.tsx
src/components/common/Header.test.tsx
src/components/common/Header.tsx
src/components/common/Input.tsx
src/containers/auth/SignUpContainer.tsx
src/containers/common/HeaderContainer.tsx
src/pages/signup.page.tsx
src/pages/signup.test.tsx

[UXUI] Sign Up 페이지에 디자인 폼을 적용하라

---

src/components/home/RecruitPosts.tsx
src/containers/detail/DetailHeaderContainer.test.tsx
src/containers/detail/DetailHeaderContainer.tsx
src/containers/home/RecruitPostsContainer.tsx
src/hooks/api/applicant/useApplyGroup.test.ts
src/hooks/api/applicant/useApplyGroup.ts
src/models/group.ts

- 사용자가 신청시 작성자에게 알람 API 플로우 추가
- Main 페이지의 글 리스트 CSS 수정

[Feature] 사용자가 신청시 작성자에게 알람에 추가되도록 하라

---

src/components/common/Header.test.tsx
src/components/common/Header.tsx
src/components/common/HeaderWrapper.test.tsx
src/components/common/HeaderWrapper.tsx
src/containers/common/HeaderContainer.tsx
src/pages/404.page.tsx
src/pages/404.test.tsx
src/pages/500.page.tsx
src/pages/500.test.tsx
src/styles/GlobalStyles.test.tsx
src/styles/GlobalStyles.tsx
src/utils/utils.test.ts
src/utils/utils.ts

[Feature] Custom 404, 500 페이지를 구현하라

---

src/assets/icons/check.svg
src/components/common/Core.tsx
src/containers/home/RecruitPostsContainer.test.tsx
src/containers/home/RecruitPostsContainer.tsx
src/hooks/api/useCatchErrorWithToast.test.ts
src/hooks/api/useCatchErrorWithToast.ts
src/styles/GlobalStyles.tsx
src/styles/StyledToastContainer.ts
src/utils/__mocks__/toast.tsx
src/utils/toast.test.tsx
src/utils/toast.tsx

- Toast Message Success & Warning 공통 컴포넌트 CSS 적용

[UI-UX] Toast Message success 및 error 컴포넌트 CSS를 적용하라

---

src/assets/icons/alert_triangle.svg
src/components/applicants/ApplicationStatusHeader.tsx
src/components/applicants/CompleteApplyFormModal.test.tsx
src/components/applicants/CompleteApplyFormModal.tsx
src/components/common/ModalWindow.test.tsx
src/components/common/ModalWindow.tsx
src/components/common/Textarea.test.tsx
src/components/common/Textarea.tsx
src/components/detail/ApplyFormModal.tsx
src/components/detail/WriterStatusButtons.test.tsx
src/components/detail/WriterStatusButtons.tsx
src/components/detail/modal/ApplicantsViewModal.test.tsx
src/components/detail/modal/ApplicantsViewModal.tsx
src/containers/applicants/ApplicationStatusHeaderContainer.test.tsx
src/containers/applicants/ApplicationStatusHeaderContainer.tsx
src/hooks/api/group/useUpdateCompletedApply.ts
src/models/group.ts
src/services/api/group.ts

- 모집 완료 후 팀원 보기 기능 구현
- 모집 완료 모달에서 메시지 입력 기능 추가
- 모집 완료 모달의 아이콘 변경

[Feature] 모집 완료 후 팀원 보기 기능 구현 및 모집 완료 시 메시지 입력 기능을 추가하라

---

package.json
src/pages/editor.page.tsx
yarn.lock

[Install] Remirror Dependencies

---

src/components/common/SwitchButton.tsx
src/components/home/RecruitPost.test.tsx
src/components/home/RecruitPost.tsx
src/containers/home/StatusBarContainer.test.tsx
src/containers/home/StatusBarContainer.tsx
src/pages/index.test.tsx
src/recoil/group/atom.ts
src/services/storage.test.ts
src/services/storage.ts

- 브라우저가 종료되어도 모집 마감 상태 안보기를 유지
- 메인 페이지의 글 아이템 CSS 깨지는 문제 수정

[Improve] 모집 마감 안보기 상태를 localStorage에 저장하여 유지시켜라

---

src/components/common/UserNavbar.tsx

- 읽지 않은 알람이 존재하지 않은 경우 알람 상태 안보이게 수정

[Fix] 읽지 않은 알람이 존재하지 않은 경우 알람 상태가 안보이게 수정하라

---

package.json
src/components/home/RecruitPost.tsx
src/components/write/WriteEditor.tsx
src/styles/GlobalStyles.tsx
src/styles/fontStyles.test.ts
src/styles/fontStyles.ts

- 에디터의 내용의 스타일을 적용한다
- H1, H2, H3... 폰트 및 사이즈 설정
- Install remirror/styles

[UI-UX] 글 작성 에디터의 Content 스타일을 적용하라

---

src/components/write/ThumbnailUpload.test.tsx
src/components/write/ThumbnailUpload.tsx

[Refactor] 누락 테스트 코드를 추가하라

---

src/components/myInfo/MyGroup.test.tsx
src/components/myInfo/MyGroup.tsx

[Feature] 마이페이지의 팀 리스트에 썸네일과 짧은 소개글을 볼 수 있게하라

---

__mocks__/firebase/storage.js
src/components/common/ConfirmModal.tsx
src/components/detail/DetailStatusButton.test.tsx
src/components/detail/DetailStatusButton.tsx
src/components/detail/WriterStatusButtons.test.tsx
src/components/detail/WriterStatusButtons.tsx
src/components/detail/modal/AskRemoveGroupModal.test.tsx
src/components/detail/modal/AskRemoveGroupModal.tsx
src/components/home/TagsBar.tsx
src/containers/home/StatusBarContainer.tsx
src/hooks/api/group/useRemoveGroup.test.ts
src/hooks/api/group/useRemoveGroup.ts
src/hooks/api/group/useUpdateCompletedApply.test.ts
src/hooks/api/storage/useRemoveGroupThumbnail.test.ts
src/hooks/api/storage/useRemoveGroupThumbnail.ts
src/services/api/__mocks__/group.ts
src/services/api/__mocks__/tagsCount.ts
src/services/api/group.test.ts
src/services/api/group.ts
src/services/api/storage.test.ts
src/services/api/storage.ts
src/services/api/tagsCount.test.ts
src/services/api/tagsCount.ts

[Feature] 글 작성한 사용자가 작성한 글을 삭제하게 하라

---

src/components/alarm/AlarmItem.test.tsx
src/components/alarm/AlarmItem.tsx
src/components/alarm/Alarms.test.tsx
src/components/alarm/Alarms.tsx
src/containers/alarm/AlarmListContainer.test.tsx
src/containers/alarm/AlarmListContainer.tsx
src/containers/applicants/ApplicationStatusHeaderContainer.test.tsx
src/containers/applicants/ApplicationStatusHeaderContainer.tsx
src/containers/detail/DetailHeaderContainer.test.tsx
src/containers/detail/DetailHeaderContainer.tsx
src/hooks/api/alarm/useUpdateAlarmViewed.test.ts
src/hooks/api/alarm/useUpdateAlarmViewed.ts
src/hooks/api/applicant/useApplyGroup.test.ts
src/hooks/api/applicant/useApplyGroup.ts
src/hooks/api/group/useUpdateCompletedApply.test.ts
src/models/alarm.ts
src/models/group.ts
src/pages/alarm.test.tsx
src/services/api/alarm.test.ts
src/services/api/alarm.ts
src/services/api/applicants.test.ts
src/utils/firestore.test.ts
src/utils/firestore.ts

- 알람 읽음 처리 로직 추가
- 알람 읽음 상태 CSS 적용
- 알람 데이터 변경

[Feature] 알람 상태 변경 로직 수정 및 추가하라

---

src/hooks/api/alarm/useFetchAlarms.ts
src/hooks/api/alarm/useFetchAlertAlarms.ts
src/hooks/api/alarm/useUpdateAlarmViewed.ts
src/hooks/api/applicant/useApplyGroup.ts
src/hooks/api/applicant/useCancelApply.ts
src/hooks/api/applicant/useFetchApplicants.ts
src/hooks/api/applicant/useUpdateApplicant.ts
src/hooks/api/auth/useFetchUserProfile.ts
src/hooks/api/auth/useSignUp.ts
src/hooks/api/comment/useAddComment.ts
src/hooks/api/comment/useDeleteComment.ts
src/hooks/api/comment/useFetchComments.ts
src/hooks/api/group/useEditGroup.ts
src/hooks/api/group/useFetchGroup.ts
src/hooks/api/group/useFetchGroups.ts
src/hooks/api/group/useFetchUserAppliedGroups.ts
src/hooks/api/group/useFetchUserRecruitedGroups.ts
src/hooks/api/group/usePublishNewGroup.ts
src/hooks/api/group/useRemoveGroup.ts
src/hooks/api/group/useUpdateCompletedApply.ts
src/hooks/api/storage/useRemoveGroupThumbnail.ts
src/hooks/api/storage/useUploadGroupThumbnail.ts
src/hooks/api/tagsCount/useFetchTagsCount.ts
src/hooks/api/useCatchFirestoreErrorWithToast.test.ts
src/hooks/api/useCatchFirestoreErrorWithToast.ts
src/hooks/api/useCatchStorageErrorWithToast.test.ts
src/hooks/api/useCatchStorageErrorWithToast.ts

- 파일 업로드 firebase storage error toast 추가

[Improve] 썸네일 에러 상태를 추가하라

---

src/assets/icons/close.svg
src/components/home/RecruitPost.tsx
src/components/myInfo/MyGroup.tsx
src/components/write/ThumbnailUpload.test.tsx
src/components/write/ThumbnailUpload.tsx
src/hooks/api/useCatchStorageErrorWithToast.test.ts
src/hooks/api/useCatchStorageErrorWithToast.ts

- 썸네일 업로드 오류 메시지 수정
- 썸네일 이미지 보이는 방식 수정
- 10MB 이상 이미지시 에러 메시지
- 썸네일 삭제 아이콘 수정

[Fix] 썸네일 디자인 피드백을 반영하라

---

package.json
src/hooks/api/group/useIncreaseView.test.ts
src/hooks/api/group/useIncreaseView.ts
src/models/group.ts
src/pages/detail/[id].page.tsx
src/pages/detail/[id].test.tsx
src/services/api/__mocks__/group.ts
src/services/api/group.test.ts
src/services/api/group.ts
yarn.lock

- 글 조회수 적용
- 하루 동안 해당 글 다시 접근시 view count X

[Feature] 글 조회수 증가를 적용하라

---

src/hooks/api/group/useIncreaseView.ts

- Update invalidate Group Query

[Fix] Update invalidate Group Query

---

package.json
yarn.lock

[Update] firebase dependency

---

src/components/alarm/AlarmsSkeletonLoader.test.tsx
src/components/alarm/AlarmsSkeletonLoader.tsx
src/components/myInfo/MyGroups.tsx
src/components/myInfo/MyGroupsSkeletonLoader.test.tsx
src/components/myInfo/MyGroupsSkeletonLoader.tsx
src/containers/alarm/AlarmListContainer.test.tsx
src/containers/alarm/AlarmListContainer.tsx
src/containers/myInfo/AppliedGroupsContainer.test.tsx
src/containers/myInfo/AppliedGroupsContainer.tsx
src/containers/myInfo/RecruitedGroupsContainer.test.tsx
src/containers/myInfo/RecruitedGroupsContainer.tsx

-  내 신청한 팀, 모집한 팀 및 알람 리스트 로딩 스켈레톤을 적용

[UI-UX] 내 신청한 팀, 모집한 팀 및 알람 리스트 로딩 스켈레톤을 적용하라

---

__mocks__/firebase/auth.js
src/components/common/ConfirmModal.tsx
src/components/myInfo/SettingForm.test.tsx
src/components/myInfo/SettingForm.tsx
src/components/myInfo/modal/AskMemberWithdrawalModal.test.tsx
src/components/myInfo/modal/AskMemberWithdrawalModal.tsx
src/containers/myInfo/MyInfoSettingContainer.test.tsx
src/containers/myInfo/MyInfoSettingContainer.tsx
src/hooks/api/auth/useAccountWithdrawal.test.ts
src/hooks/api/auth/useAccountWithdrawal.ts
src/pages/myinfo/setting.test.tsx
src/services/api/__mocks__/auth.ts
src/services/api/auth.test.ts
src/services/api/auth.ts

- 가입한 사용자는 회원 탈퇴
- 회원 탈퇴시 탈퇴 확인 모달창

[Feature] 가입한 사용자는 회원 탈퇴를 할 수 있게하라

---

package.json
src/components/common/HeaderWrapper.tsx
src/components/common/UserNavbar.test.tsx
src/components/common/UserNavbar.tsx
src/components/home/RecruitPost.tsx
src/containers/home/StatusBarContainer.test.tsx
src/containers/home/StatusBarContainer.tsx
src/pages/index.page.tsx
src/styles/responsive.ts
src/test/InjectMockProviders.tsx
yarn.lock

- 헤더와 글 리스트에 반응형을 적용
- Install react-responsive

[UI-UX] 헤더와 글 리스트에 반응형을 적용하라

---

src/components/common/HeaderWrapper.test.tsx
src/components/common/HeaderWrapper.tsx
src/components/common/Tag.test.tsx
src/components/common/Tag.tsx
src/components/detail/DetailContentsSection.test.tsx
src/components/detail/DetailContentsSection.tsx
src/components/home/TagsBar.test.tsx
src/components/home/TagsBar.tsx
src/containers/detail/DetailContentsContainer.test.tsx
src/models/group.ts
src/recoil/group/atom.ts
src/services/firebase/getQuery.test.ts
src/services/firebase/getQuery.ts
src/test/InjectTestingRecoilState.tsx

- 태그 클릭시 메인 페이지의 글 리스트가 필터링
- 모집 완료 미완료 필터링, 카테고리, 태그 중복 필터링 적용

[Feature] 태그 클릭시 메인 페이지의 글 리스트가 필터링이 가능하도록 하라

---

.eslintrc.js
.storybook/main.js
.storybook/preview.js
package.json
src/components/common/Button.stories.tsx
src/components/common/ConfirmModal.stories.tsx
src/components/common/CreatableSelectBox.stories.tsx
src/components/common/DropDown.stories.tsx
src/components/common/EmptyStateArea.stories.tsx
src/stories/Button.stories.tsx
src/stories/Header.stories.tsx
src/stories/Page.stories.tsx
yarn.lock

- Button
- DropDown
- EmptyStateArea
- ConfirmModal
- CreatableSelectBox

[Add] Storybook에 공통 컴포넌트를 추가하라

---

.storybook/main.js
package.json
src/components/common/SelectBox.stories.tsx
src/components/common/SkeletonItem.stories.tsx
src/components/common/SubHeader.stories.tsx
src/components/common/Tag.stories.tsx
src/components/common/ViewModalWindow.stories.tsx
src/stories/Color.stories.mdx
yarn.lock

- SelectBox
- SkeletonItem
- SubHeader
- TagViewModalWindow
- color
- Install @storybook/addon-docs dependency

[UIUX] 공통 컴포넌트를 storybook에 정리하라

---

src/components/write/WriteEditor.tsx

- Editor selection 속성의 스타일이 보이지 않는 문제를 수정

[Fix] Editor selection 속성의 스타일이 보이지 않는 문제를 수정하라

---

jest.config.js
next.config.js
package.json
src/hooks/api/auth/useAuthIdToken.ts
src/hooks/api/auth/useAuthUser.ts
src/hooks/api/auth/useGetUser.test.ts
src/hooks/api/auth/useGetUser.ts
src/hooks/api/auth/useGetUserToken.test.ts
src/hooks/api/auth/useGetUserToken.ts
yarn.lock

- 두개의 hook인 firebase auth를 사용했는데 해당 hook을 따로 빼고, dependency를 제거
- 해당 hook은 테스트할 이유가 없기때문에 test coverage에서 제외
- next.config.js 세팅 수정

[Refactor] @react-query-firebase/auth dependency를 제거하라

---

__mocks__/firebase/firestore.js
src/components/myInfo/MyGroups.tsx
src/hooks/api/group/useInfiniteFetchUserRecruitedGroups.test.ts
src/hooks/api/group/useInfiniteFetchUserRecruitedGroups.ts
src/models/index.ts
src/services/api/__mocks__/group.ts
src/services/api/group.test.ts
src/services/api/group.ts
src/utils/utils.test.ts
src/utils/utils.ts

- Implement getInfiniteUserRecruitedGroups API
- 내가 신청한 스터디 리스트에 대한 API hook 구현

[Feature] 내가 신청한 스터디 리스트에 대한 API를 무한 스크롤이 가능하도록 하라

---

src/hooks/api/alarm/useFetchAlarms.test.ts
src/hooks/api/alarm/useFetchAlarms.ts
src/hooks/api/alarm/useFetchAlertAlarms.test.ts
src/hooks/api/alarm/useFetchAlertAlarms.ts
src/hooks/api/applicant/useFetchApplicants.test.ts
src/hooks/api/applicant/useFetchApplicants.ts
src/hooks/api/comment/useFetchComments.test.ts
src/hooks/api/comment/useFetchComments.ts
src/hooks/api/group/useFetchGroup.ts
src/hooks/api/group/useFetchGroups.test.ts
src/hooks/api/group/useFetchGroups.ts
src/hooks/api/group/useFetchUserAppliedGroups.test.ts
src/hooks/api/group/useFetchUserAppliedGroups.ts
src/hooks/api/group/useFetchUserRecruitedGroups.test.ts
src/hooks/api/group/useFetchUserRecruitedGroups.ts
src/hooks/api/tagsCount/useFetchTagsCount.test.ts
src/hooks/api/tagsCount/useFetchTagsCount.ts

- Api hook에 util 함수 checkEmpty을 적용

[Refactor] Api hook에 util 함수 checkEmpty을 적용하라

---

__mocks__/react-intersection-observer.js
package.json
src/hooks/api/group/useInfiniteFetchUserAppliedGroups.test.ts
src/hooks/api/group/useInfiniteFetchUserAppliedGroups.ts
src/services/api/__mocks__/applicants.ts
src/services/api/applicants.test.ts
src/services/api/applicants.ts
yarn.lock

- Implement getInfiniteUserAppliedGroups API and hook
- Install react-intersectio-observer dependency
- Change to infinite scroll api hook with react-intersection-observer

[Feature] 내가 참여한 스터디 리스트에 대한 API를 무한 스크롤이 가능하도록 하라

---

src/components/myInfo/MyGroups.test.tsx
src/components/myInfo/MyGroups.tsx
src/components/myInfo/MyGroupsSkeletonLoader.tsx
src/containers/myInfo/AppliedGroupsContainer.tsx
src/containers/myInfo/RecruitedGroupsContainer.tsx

- Infinite scroll 시 다음 페이지 로딩시 스켈레톤 로딩을 적용

[Feature] 내 정보 페이지의 신청 및 모집 리스트에 스켈레톤 로딩을 적용하라

---

.github/workflows/lighthouse.yaml
.github/workflows/lighthouse.yml
.gitignore
lighthouserc.js

- github action lighthouse CI를 적용

[Setting] 성능 측정 도구인 github action lighthouse CI를 적용하라

---

.github/workflows/lighthouse.yml
.gitignore
lighthouserc.js

- CI 단계에서 lighthouse comment를 추가

[Setting] Lighthouse CI에 comment를 추가하라

---

tsconfig.json

[Fix] Broken jest expect types

---

.github/workflows/lighthouse.yml
.gitignore
next.config.js
package.json
sentry.client.config.js
sentry.properties
sentry.server.config.js
src/pages/_error.page.jsx
yarn.lock

- production 환경에서만 tracking되도록 sentry 적용

[Feature] Error tracking 도구인 Sentry를 적용하라

---

package.json
yarn.lock

[Feature] Update next.js dependecies

---

yarn.lock

- fix dependency
- https://github.com/jennie-harang/Conners/pull/398

chore: fix dependency

---

src/components/common/UserNavbar.tsx
src/containers/home/StatusBarContainer.tsx
src/hooks/useResponsive.test.tsx
src/hooks/useResponsive.ts
src/styles/responsive.ts
src/test/InjectResponsiveContext.tsx

- react-responsive hydrate error 이슈 수정
- useResponsive custom hook 구현
- useLayoutEffect hydrate console error를 제거하기 위해 useIsomorphicLayoutEffect hook 사용

fix: react-responsive 사용시 발생하는 ssr hydrate error를 수정하라

---

.github/workflows/nextjs_bundle_analysis.yml
next.config.js
package.json
yarn.lock

- ci 단계에서 번들 사이즈를 측정하기 위해 nextjs bundle analysis를 세팅

perf: ci 단계에서 번들 사이즈를 측정하기 위해 nextjs bundle analysis를 세팅하라

---

.husky/commit-msg
.lintstagedrc.json
commitlint.config.js
package.json
yarn.lock

- commitlint를 적용
- husky로 commit lint 체크

ci: commitlint husky를 적용하라

---

yarn.lock

- Cleans up yarn.lock by removing duplicates with yarn-deduplicate
- https://www.npmjs.com/package/yarn-deduplicate

chore: cleans up yarn.lock by removing duplicates

---

.dockerignore
Dockerfile
next.config.js

- docker 사용해보기 테스트.
- output standalone option

chore: docker test

---

src/components/common/SelectBox.stories.tsx
src/components/common/SelectBox.test.tsx
src/components/common/SelectBox.tsx
src/components/home/FilterBar.test.tsx
src/components/home/FilterBar.tsx
src/containers/home/StatusBarContainer.tsx
src/services/api/index.ts

- select box 공통 컴포넌트에 value props 추가
- 만약 값이 변경되는 경우 selectbox option이 update되도록 수정

fix: 홈 로고 클릭시 필터되어있는 selectbox가 초기값으로 clear되어야하는데 유지되는 이슈를 수정하라

---

package.json
src/components/write/RemirorEditorProvider.tsx
src/components/write/WriteEditor.tsx

- 글 작성시 트위터 이모지가 적용되는데 해당 부분을 제거하여 번들사이즈를 감소

perf: svgmoji를 걷어내 번들사이즈를 감소시켜라

---

package.json
src/components/alarm/Alarms.tsx
src/components/applicants/ApplicationStatus.tsx
src/components/common/UserNavbar.tsx
src/components/detail/CommentView.tsx
src/components/detail/DetailStatusButton.tsx
src/components/home/RecruitPosts.tsx
src/components/myInfo/MyGroups.tsx
src/components/write/ThumbnailUpload.tsx
src/containers/write/PublishModalContainer.tsx
src/utils/utils.test.ts
src/utils/utils.ts
yarn.lock

- 거의 사용되지 않는 ramda.js를 걷어낸다.
- isEmpty util함수 구현

chore: ramda js를 걷어내라

---

src/components/alarm/AlarmsSkeletonLoader.tsx
src/components/common/Header.tsx
src/components/common/ProfileImage.tsx
src/components/common/SkeletonItem.stories.tsx
src/components/common/SkeletonItem.tsx
src/components/detail/CommentSkeletonLoader.test.tsx
src/components/detail/CommentSkeletonLoader.tsx
src/components/detail/CommentsView.test.tsx
src/components/detail/CommentsView.tsx
src/components/home/RecruitPostsSkeletonLoader.tsx
src/components/home/TagsBar.tsx
src/components/myInfo/MyGroupsSkeletonLoader.tsx
src/hooks/api/comment/useAddComment.ts

feat: 댓글 로딩시에 로딩스켈레톤을 젹용하라

---

src/components/home/RecruitPostsSkeletonLoader.tsx

- 스타일 수정
- 모바일에서 메인 리스트 스켈레톤 로딩이 깨지는 이슈 수정
- layout 추가 및 overflow hidden 추가

style: 모바일에서 메인 리스트 스켈레톤 로딩이 깨지는 이슈를 수정하라

---

jest.config.js
jest.setup.js
src/assets/icons/check.svg
src/components/alarm/AlarmItem.tsx
src/components/common/CloseButton.tsx
src/components/common/Core.test.tsx
src/components/common/Core.tsx
src/components/detail/CommentView.tsx
src/components/detail/DetailHeaderSection.tsx
src/components/home/RecruitPost.tsx
src/components/myInfo/MyGroup.tsx
src/containers/applicants/ApplicationStatusHeaderContainer.tsx
src/hooks/useRecruitDateStatus.ts
src/pages/_app.page.tsx
src/styles/GlobalStyles.tsx
src/styles/StyledToastContainer.tsx
src/utils/toast.test.tsx
src/utils/toast.tsx

style: 토스트메시지 스타일을 변경하라

---

src/components/auth/SignInModal.tsx

- 모바일 환경일 경우 sign in 모달이 아래에 고정되어 보여지도록 반영

style: sign in 모달에 반응형을 적용하라

---

src/components/write/EditorToolbar.tsx
src/components/write/TagForm.tsx
src/components/write/WriteEditor.tsx
src/components/write/WriteForm.tsx
src/containers/write/WriteFormContainer.test.tsx
src/containers/write/WriteFormContainer.tsx
src/styles/responsive.ts

- 글 작성하기 페이지에 모바일 대응하는 반응형 페이지 적용

style: 글 작성 페이지에 반응형을 적용하라

---

src/components/applicants/ApplicationStatusHeader.tsx
src/components/common/UserNavbar.tsx
src/components/detail/ApplicantStatusButton.tsx
src/components/detail/WriterStatusButtons.tsx
src/components/myInfo/SettingForm.tsx
src/components/write/WriteEditor.tsx
src/containers/common/HeaderContainer.tsx
src/hooks/useBoolean.test.ts
src/hooks/useBoolean.ts

- 특히 모달이 열리고 닫히고하는 state를 관리하는 boolean을 검증하는 useState가 중복적으로 함수 호출이 일어난다.
- useBoolean custom hook을 구현하여 리팩터링하기

refactor: useBoolean custom hook을 구현하라

---

src/components/applicants/CompleteApplyFormModal.test.tsx
src/components/applicants/CompleteApplyFormModal.tsx
src/components/auth/SignUpForm.tsx
src/components/common/FormModal.test.tsx
src/components/common/FormModal.tsx
src/containers/auth/SignUpContainer.tsx
src/styles/StyledToastContainer.tsx
src/test/InjectResponsiveContext.tsx
src/utils/__mocks__/toast.tsx
src/utils/toast.tsx

- 폼 모달에 반응형 적용
- toast bottom up style 추가

style: 모집 완료 모달창 반응형을 적용하라

---

src/components/common/FormModal.stories.tsx
src/components/common/FormModal.tsx
src/components/write/PublishModalForm.test.tsx
src/components/write/PublishModalForm.tsx
src/components/write/RemirorEditorProvider.tsx
src/containers/write/PublishModalContainer.test.tsx

- 팀 모집할 때 분류, 모집 종료 설정, 시간 설정 안했을 경우 버튼 disabled
- 글 등록 모달 제목이 긴 경우 대응 추가

feat: 글 등록 시 유효성 검사 로직을 추가하라

---

src/components/common/ConfirmModal.test.tsx
src/components/common/ConfirmModal.tsx

style: confirm modal에 반응형을 적용하라

---

src/components/home/TagsBar.test.tsx
src/components/home/TagsBar.tsx
src/components/home/skeleton/TagsBarSkeletonLoader.test.tsx
src/components/home/skeleton/TagsBarSkeletonLoader.tsx
src/containers/home/StatusBarContainer.test.tsx
src/containers/home/StatusBarContainer.tsx
src/hooks/api/tagsCount/useFetchTagsCount.test.tsx
src/hooks/api/tagsCount/useFetchTagsCount.ts
src/test/ReactQueryWrapper.tsx

- react suspense 적용
- useFetchTagsCount api hook에 suspense 적용

perf: main 페이지의 tag filter bar에 concurrent mode를 적용하라

---

.github/workflows/ci.yml

- PR은 변경된 파일에 대해서만
- main 브랜치에 merge된 경우 모든 파일에 대해서

ci: main 브랜치에 merge가 된 경우 모든 테스트 커버리지가 동작하도록 추가하라

---

package.json
yarn.lock

- remove unused ramda dependency

chore: remove unused ramda dependency

---

src/components/common/SubHeader.test.tsx
src/components/common/SubHeader.tsx
src/components/write/EditorToolbar.tsx

- 툴바에서 맨 마지막 및 처음에 툴바가 안눌리는 경우 수정
- header의 제목에 transition적용

fix: 모바일일 경우 글 작성 해더 이슈 수정를 수정하라

---

src/components/detail/DetailContentsSection.test.tsx
src/components/detail/DetailContentsSection.tsx

feat: 글에 썸네일이 존재하는 경우 글 상단에 썸네일 이미지가 나타나도록 하라

---

src/components/common/ViewModalWindow.test.tsx
src/components/common/ViewModalWindow.tsx
src/components/detail/WriterStatusButtons.tsx
src/components/detail/modal/MembersViewModal.test.tsx
src/components/detail/modal/MembersViewModal.tsx

- 모집 완료 후 팀원 보기 모달창 반응형 적용
- 팀원 보기 모달창이 띄워져있을 경우 스크롤이 일어나지 않도록 변경

style: 팀원 보기 모달창 반응형을 적용하라

---

src/components/write/PublishModalForm.test.tsx
src/components/write/PublishModalForm.tsx

- 팀 모집하기 등록하기 모달 모바일 대응
- 짧은 소개글 error 상태 수정

style: 팀 모집하기의 등록하기(수정하기) 모달에 반응형을 적용하라

---

src/components/auth/SignInModal.tsx
src/components/common/ConfirmModal.tsx
src/components/common/FormModal.tsx

style: 모달 및 팝업이 보이는 경우 스크롤 고정시켜라

---

src/components/detail/ApplicantStatusButton.test.tsx
src/components/detail/ApplicantStatusButton.tsx
src/components/detail/DetailHeaderSection.test.tsx
src/components/detail/DetailHeaderSection.tsx
src/components/detail/DetailStatusButton.test.tsx
src/components/detail/DetailStatusButton.tsx
src/components/detail/WriterStatusButtons.test.tsx
src/components/detail/WriterStatusButtons.tsx
src/pages/detail/[id].page.tsx
src/styles/Layout.tsx

- 글 상세 페이지 반응형 적용
- 버튼을 하단에 fixed로 style 수정

style: 글 상세페이지에 반응형을 적용하라

---

src/components/common/ConfirmModal.tsx
src/components/common/ViewModalWindow.tsx
src/components/detail/DetailContentsSection.tsx
src/components/detail/DetailHeaderSection.tsx
src/components/detail/DetailStatusButton.tsx
src/components/detail/WriterStatusButtons.tsx
src/styles/Divider.ts
src/styles/zIndexes.ts

- 팀원보기 모달 border-radius 제거
- 회원탈퇴 모달 description 스타일 수정
- 상세 페이지 내용 min height 260px
- 상세 페이지 헤더 부분 내용이 화면에 넘칠경우 ...처리

style: 반응형시 사소한 ux이슈를 수정하라

---

src/components/applicants/CompleteApplyFormModal.tsx
src/components/common/FormModal.tsx
src/components/common/HeaderWrapper.tsx
src/components/detail/ApplyFormModal.tsx
src/components/detail/DetailStatusButton.tsx
src/components/detail/WriterStatusButtons.tsx
src/components/detail/modal/MembersViewModal.tsx
src/components/write/PublishModalForm.tsx
src/pages/detail/[id].page.tsx
src/styles/responsive.ts

1. 팀 모집하기 > 등록 / 수정 모달이 모바일에서 스크롤이 일어나지 않는 이슈 수정
2. 모바일일 때 bottom fixed 때문에 댓글이 짤려서 보이는 현상 수정

fix: 반응형 적용 스타일에서 깨지는 이슈를 수정하라

---

src/components/common/FormModal.tsx

fix: form modal이 pc화면일 경우에만 body scroll이 고정되도록 수정하라

---

src/components/common/FormModal.tsx
src/styles/GlobalStyles.tsx

- 모바일 (ios)에서 기본으로 적용되어있는 스타일을 없앤다.
- 모달의 header의 bottom box shadow가 input에 안보이는 이슈 z index 수정

fix: 팀 모집하기 모달의 z index 이슈와 date type input width를 수정하라

---

src/components/applicants/ApplicationStatusHeader.test.tsx
src/components/auth/SignInModal.tsx
src/components/common/ConfirmModal.tsx
src/components/common/FormModal.tsx
src/components/common/ViewModalWindow.tsx
src/components/detail/ApplicantStatusButton.test.tsx
src/components/detail/DetailStatusButton.test.tsx
src/components/detail/DetailStatusButton.tsx
src/components/detail/WriterStatusButtons.test.tsx
src/components/myInfo/SettingForm.test.tsx
src/containers/auth/SignInModalContainer.test.tsx
src/containers/write/PublishModalContainer.test.tsx

- 로그인 모달
- confirm modal
- 등록하기 및 form modal
- 팀원보기 모달
- 열리고 닫힐때 애니메이션을 적용
- 모바일일 경우 아래에서 위로 나타난다.

style: 모든 모달 컴포넌트에 애니메이션을 적용하라

---

src/components/detail/modal/MembersViewModal.tsx

- 팀원 보기 모달에서 링크가 긴 경우 `...` 처리
- 스크롤 발생시 하단에 그라에이션을 추가

style: 팀원 보기 모달에 링크가 긴 경우 및 스크롤 그라데이션을 추가하라

---

src/components/applicants/ApplicantItem.tsx
src/components/common/Textarea.test.tsx
src/components/common/Textarea.tsx
src/components/detail/CommentView.tsx
src/components/detail/DetailContentsSection.tsx

- TextArea를 입력하는 시점에는 Enter 적용 가능하도록 변경
- 댓글, 신청 시 소개글, 팀원들에게 보내는 메시지는 Enter 적용해서 보여주고 짧은 소개글만 띄어쓰기 적용해서 보여주기

chore: 모달에서 textarea에서 enter 클릭시 줄바꿈을 적용하라

---

src/components/auth/SignInModal.tsx
src/components/common/ConfirmModal.tsx
src/components/common/FormModal.tsx
src/components/common/ViewModalWindow.tsx
src/styles/transitions.ts

- Dialog 모달은 외부 영역 클릭 시 사라진다
- bottom up animation 변경
- pc일 때 fade in out animation 수정 및 적용

style: 모달 에니메이션 수정 및 Dialog 모달은 외부 영역 클릭 시 사라지록하라

---

src/components/common/SkeletonItem.tsx
src/components/myInfo/MyGroup.tsx
src/components/myInfo/MyGroupsSkeletonLoader.tsx
src/components/myInfo/MyInfoTab.tsx
src/containers/myInfo/MyInfoTabContainer.tsx

- 내 정보 > 신청한 팀, 모집한 팀 리스트 반응형 적용
- 스켈레톤 반응형 적용

style: 내 정보 페이지의 신청한 팀, 모집한 팀 리스트에 반응형을 적용하라

---

src/components/applicants/ApplicantItem.test.tsx
src/components/applicants/ApplicantItem.tsx
src/components/applicants/ApplicationStatus.tsx
src/components/applicants/ApplicationStatusHeader.test.tsx
src/components/applicants/ApplicationStatusHeader.tsx
src/containers/applicants/ApplicationStatusContainer.test.tsx
src/containers/applicants/ApplicationStatusContainer.tsx

style: 신청 현황 페이지에 반응형을 적용하라

---

README.md

- 변경된 react-query dependency badge 업데이트

docs: react-query dependency badge를 업데이트하라

---

src/components/home/RecruitPost.test.tsx
src/components/home/RecruitPost.tsx

- 글 리스트에 썸네일이 존재하면 짧은 소개글이 2줄
- 썸네일이 존재하지 않으면 4줄 유지

fix: 글 리스트에 썸네일이 존재하면 짧은 소개글이 2줄까지만 나오도록 수정하라

---

@types/react.d.ts

- react.d.ts memo typescript 추가

chore: react memo의 generic 타입을 알지를 못해서 전역에 memo 타입을 추가하라

---

src/components/detail/CommentForm.test.tsx
src/components/detail/CommentForm.tsx

- 모바일 디바이스에서 댓글 남기기 버튼 사이즈를 Small 사이즈로 변경

fix: 모바일 사이즈에서 댓글 남기기 버튼의 사이즈를 변경해야하는 이슈를 반영하라

---

src/components/applicants/ApplicationStatusHeader.tsx

- ssr인 경우에 window객체가 없어서 모바일 상태인지 확인하지 못하기 때문에 발생하는 문제
- window 전역 객체가 존재할 때 버튼이 보이도록 수정

fix: 신청현황에서 하단 플로팅 버튼 사이즈가 로딩되면서 바뀌는 이슈를 수정하라

---

src/components/common/SelectBox.tsx

- select box medium size를 변경된 디자인을 반영

style: select box 스타일을 변경된 디자인을 적용하라

---

src/components/auth/SignInModal.tsx
src/components/common/ConfirmModal.tsx
src/components/common/FormModal.tsx
src/components/common/ViewModalWindow.tsx
src/styles/animations.test.ts
src/styles/animations.ts
src/styles/transitions.ts

- 모달 background에 fade in out animation 추가
- 모달 animation 중복되는 스타일 공통화 (refactor)

style: 모달이 닫히고 열릴때 background 색이 서서히 나타나고 사라지도록 변경하라

---

src/components/detail/DetailContentsSection.tsx
src/components/write/ThumbnailUpload.tsx
src/hooks/useResponsive.test.tsx
src/styles/responsive.ts

- 모바일 기준을 450px => 500px로 변경
- 상세 페이지 썸네일 이미지 max height를 500px 적용

style: 모바일 기준 변경 및 상세 페이지 썸네일 이미지를 max height를 적용하라

---

src/components/common/SubHeader.tsx
src/components/detail/WriterStatusButtons.tsx
src/hooks/useActionKeyEvent.test.ts
src/hooks/useActionKeyEvent.ts

- 하나의 key가 아닌 경우 대응하기 위해서 배열로 key code를 받아서 처리하도록 리팩터링

refactor: useActionKeyEvent hook을 배열을 받아 사용할 수 있도록 리팩터링하라

---

@types/environment.d.ts
__mocks__/setEnvVars.js
jest.config.js
src/containers/myInfo/MyInfoSettingContainer.test.tsx
src/containers/myInfo/MyInfoSettingContainer.tsx

- fix Incomplete URL substring sanitization
- firebase storage host NEXT_PUBLIC_FIREBASE_STORAGE_URL로 사용

fix: incomplete url substring sanitization 이슈를 해결하라

---

src/components/myInfo/ImageSetting.test.tsx
src/components/myInfo/ImageSetting.tsx
src/containers/myInfo/MyInfoSettingContainer.test.tsx
src/containers/myInfo/MyInfoSettingContainer.tsx
src/styles/GlobalStyles.tsx

- 이미지 변경 버튼 클릭시 사용자 프로필 이미지 변경
- 이미지가 이미 존재한 경우에는 기존의 이미지 삭제 후 새로운 이미지 업로드

feat: 내 정보 수정에 이미지 변경 로직을 구현하라

---

src/components/myInfo/ImageSetting.tsx
src/containers/myInfo/MyInfoSettingContainer.test.tsx
src/containers/myInfo/MyInfoSettingContainer.tsx
src/hooks/api/auth/useUpdateUser.ts
src/hooks/api/comment/useDeleteComment.ts
src/hooks/useRenderSuccessToast.test.ts
src/hooks/useRenderSuccessToast.ts

- 토스트 메시지 hook 리팩터링
- 이미지 삭제 및 업로드 성공시 토스트 메시지 렌더링

feat: 이미지 삭제 및 업로드에 성공하면 토스트 메시지가 나타나도록 하라

---

src/components/common/CreatableSelectBox.tsx
src/components/myInfo/SettingForm.test.tsx
src/components/myInfo/SettingForm.tsx
src/containers/myInfo/MyInfoSettingContainer.test.tsx
src/containers/myInfo/MyInfoSettingContainer.tsx

- input field의 react-hook-form 적용
- validate 적용
- 해당 테스트 수정

feat: 내 정보 수정 페이지에서 내 정보를 수정 폼을 적용하라

---

src/components/myInfo/SettingForm.test.tsx
src/components/myInfo/SettingForm.tsx
src/containers/myInfo/MyInfoSettingContainer.test.tsx
src/containers/myInfo/MyInfoSettingContainer.tsx

- 내 정보 수정 페이지의 저장하기 클릭시 프로필 정보 수정
- update profile 적용

feat: 내 정보 수정하기 api form action을 적용하라

---

src/components/applicants/ApplicationStatusSkeletonLoader.test.tsx
src/components/applicants/ApplicationStatusSkeletonLoader.tsx
src/containers/applicants/ApplicationStatusContainer.tsx

- 신청현황 페이지 모바일, 데스크탑 로딩 스켈레톤 적용

style: 신청현황 페이지에 스켈레톤 로딩을 적용하라

---

src/components/detail/CommentsView.test.tsx
src/components/detail/CommentsView.tsx
src/containers/detail/CommentsContainer.test.tsx
src/containers/detail/CommentsContainer.tsx
src/hooks/api/comment/useInfiniteFetchComments.test.ts
src/hooks/api/comment/useInfiniteFetchComments.ts

refactor: 댓글 리스트에 concurrent mode를 적용하라

---

src/containers/alarm/AlarmListContainer.test.tsx
src/containers/alarm/AlarmListContainer.tsx
src/hooks/api/alarm/useInfiniteFetchAlarms.test.ts
src/hooks/api/alarm/useInfiniteFetchAlarms.ts
src/pages/alarm.page.tsx
src/pages/alarm.test.tsx

- 내 알람 리스트에 concurrent suspense 적용

refactor: 내 알람 페이지에 concurrent mode를 적용하라

---

src/components/write/PublishModalForm.tsx
src/components/write/WriteForm.tsx
src/containers/home/StatusBarContainer.tsx
src/containers/write/PublishModalContainer.tsx
src/containers/write/WriteFormContainer.tsx
src/models/index.ts

- 기존에 사용되던 Keypair type을 Partial 타입스크립트 내장 타입으로 대체
- KeyPair type 제거

refactor: 사용하지 않는 타입을 제거하라

---

src/hooks/api/group/useInfiniteFetchGroups.test.ts
src/hooks/api/group/useInfiniteFetchGroups.ts
src/pages/api/groups.api.ts
src/pages/api/groups.test.ts
src/services/api/group.test.ts
src/services/api/group.ts
src/utils/__mocks__/firestore.ts
src/utils/firestore.test.ts
src/utils/firestore.ts

- infinite scroll 적용으로 인해 csr로 반영되었던 api를 ssr로 변경

feat: 메인 페이지 리스트 infinite scroll api에 ssr을 적용하라

---

src/stories/Typography.stories.mdx
src/styles/fontStyles.test.ts
src/styles/fontStyles.ts

docs: 스토리북에 typography를 추가하라

---

src/components/write/WriteEditor.tsx

- pc 화면에서는 height가 500px이상 되면 에디터에 스크롤이 발생하도록 변경

style: pc 화면에서 글 작성 에디터의 max-height는 500px이도록 변경하라

---

README.md

- https://github.com/badges/shields/issues/8671
- change to github action workflow badge

docs(badge): change to github action workflow badge

---

.storybook/preview.jsx
next.config.js
src/components/applicants/ApplicantItem.test.tsx
src/components/applicants/ApplicantItem.tsx
src/components/common/EmptyStateArea.test.tsx
src/components/common/EmptyStateArea.tsx
src/components/common/ProfileImage.test.tsx
src/components/common/ProfileImage.tsx
src/components/detail/DetailContentsSection.tsx
src/components/detail/DetailHeaderSection.test.tsx
src/components/detail/DetailHeaderSection.tsx
src/components/detail/modal/MembersViewModal.tsx
src/components/home/RecruitPost.test.tsx
src/components/home/RecruitPost.tsx
src/components/myInfo/ImageSetting.tsx
src/components/myInfo/MyGroup.test.tsx
src/components/myInfo/MyGroup.tsx
src/components/write/ThumbnailUpload.test.tsx
src/components/write/ThumbnailUpload.tsx

- next/image 적용
- emptyStateArea만 제외
- https://nextjs.org/docs/api-reference/next/image

perf(image): img태그를 next image로 변경하라

---

src/components/common/ProfileImage.tsx
src/components/detail/DetailContentsSection.tsx
src/components/home/RecruitPost.tsx
src/components/myInfo/ImageSetting.tsx
src/components/myInfo/MyGroup.tsx
src/components/write/ThumbnailUpload.tsx
src/utils/imageBlur.test.ts
src/utils/imageBlur.ts

- base64기반의 shimmer svg blur이미지 적용
- https://nextjs.org/docs/api-reference/next/image#blurdataurl

perf(image): next image에 blurDataURL을 적용하라

---

@types/sentry.d.ts
src/components/common/ErrorBoundary.test.tsx
src/components/common/ErrorBoundary.tsx
src/containers/home/RecruitPostsContainer.tsx
src/containers/home/StatusBarContainer.test.tsx
src/containers/home/StatusBarContainer.tsx
src/hooks/api/group/useInfiniteFetchGroups.ts
src/hooks/api/tagsCount/useFetchTagsCount.ts
src/pages/_app.page.tsx

- ErrorBoundary 공통 컴포넌트를 구현
- Sentry ErrorBoundary 사용
- main 페이지의 태그 리스트 error boundary 적용
- main 글 리스트에 error boundary 적용

feat(ErrorBoundary): errorBoundary 공통 컴포넌트를 구현 및 메인 페이지에 적용하라

---

package.json
src/pages/test.page.tsx
src/pages/test.test.tsx
yarn.lock

- install react-type-animation dependency
- /test에 sample type animation 추가

chore: react-type-animation

---

src/pages/test.page.tsx

- typing animation 커서 디자인 피드백 반영

style: typing animation 커서 스타일을 변경하라

---

public/naver246867b457f890a4f2e4bda095ffc7dc.html

- 네이버 seo 웹 마스터 사이트 소유권 확인을 위한 html 파일을 추가

chore: 네이버 seo 웹 마스터 사이트 소유권 확인을 위한 html 파일을 추가하라

---

src/components/home/RecruitPostsSkeletonLoader.tsx
src/containers/home/RecruitPostsContainer.tsx
src/containers/home/StatusBarContainer.tsx
src/recoil/atomEffects.test.ts
src/recoil/atomEffects.ts
src/recoil/group/atom.ts
src/services/storage.test.ts

- localStorage와 recoil을 같이 사용하는 state를 atom effect로 관리
- localStorageEffect 구현

refactor: localStorage와 recoil을 같이 사용하는 state를 atom effect로 관리하라

---

src/components/detail/CommentsView.test.tsx
src/components/home/RecruitPost.test.tsx
src/components/home/RecruitPost.tsx
src/components/home/RecruitPosts.tsx
src/components/myInfo/MyGroup.tsx
src/components/write/ThumbnailUpload.tsx

- next image placeholder blur처리 => empty로 변경

refactor: next image placeholder blur처리를 제거하라
