src/components/new/PublishModalForm.test.tsx, src/components/new/PublishModalForm.tsx, src/components/new/TagForm.test.tsx, src/components/new/TagForm.tsx, src/containers/new/PublishModalContainer.test.tsx, src/containers/new/PublishModalContainer.tsx
- keydown은 이벤트가 두 번 발생하여, enter 입력시 keypress 사용
- keydown은 backspace 채크와 , 입력시 태그 등록
- 하지만, 쉼표는 여전히 이벤트 두번 발생.
=> [Fix] 태그 등록 시 keypress, keydown 한글 입력시 생기는 버그 수정

.eslintrc.js, src/components/new/NewHeader.test.tsx, src/components/new/NewWriteForm.test.tsx, src/components/new/PublishModalForm.test.tsx, src/components/new/PublishModalForm.tsx
- 모집 종료 설정이 "입력한 시간에 자동으로 종료" 시 모집 종료 일시 입력
- 모집 종료 설정이 자동으로 입력이 아닐 때 모집 종료 일시 disabled
=> [Improve] 모집 종료 설정(조건)에 따라 종료 일시를 변경하여 입력하게 하라

fixtures/group.ts, fixtures/initialStore.ts, next.config.js, src/containers/detail/DetailHeaderContainer.test.tsx, src/containers/detail/DetailHeaderContainer.tsx, src/containers/new/NewHeaderContainer.test.tsx, src/containers/new/NewHeaderContainer.tsx, src/models/group.ts, src/pages/detail/[id].page.tsx, src/pages/detail/[id].test.tsx, src/reducers/groupSlice.test.ts, src/reducers/groupSlice.ts, src/reducers/rootReducer.test.ts, src/services/api/__mocks__/group.ts, src/services/api/group.test.ts, src/services/api/group.ts, src/utils/__mocks__/utils.ts, src/utils/utils.test.ts, src/utils/utils.ts
- detail 페이지 구현
- serverside로 params.id 값으로 정보 조회.
- 조회 후 존재하면 redux store에 담김
- 존재하지 않으면 404
=> [Feature] 스터디(프로젝트) 글 등록 후 해당 detail 페이지로 이동하게 하라

src/services/firebase/firebaseConfig.ts
- next.js에서 브라우저 환경에서 environment에 접근하려면, `NEXT_PUBLIC` 접두어가 붙어야한다.
- https://nextjs.org/docs/basic-features/environment-variables#exposing-environment-variables-to-the-browser
=> [Fix] Production 환경에서 firestore에 접근하지 못하는 오류를 수정하라

fixtures/group.ts, fixtures/initialStore.ts, src/components/detail/DetailHeaderSection.test.tsx, src/components/detail/DetailHeaderSection.tsx, src/containers/detail/DetailHeaderContainer.test.tsx, src/containers/detail/DetailHeaderContainer.tsx, src/containers/write/PublishModalContainer.tsx, src/models/group.ts, src/pages/api/auth/[...nextauth].api.ts, src/pages/detail/[id].page.tsx, src/pages/detail/[id].test.tsx, src/reducers/groupSlice.test.ts, src/reducers/groupSlice.ts, src/reducers/rootReducer.test.ts, src/reducers/store.ts, src/services/api/group.test.ts, src/services/api/group.ts, types/next-auth.d.ts
- 기존에 writerUid로 작성자 정보를 조회했다. 생각보다 이렇게 했을 때 firestore 구조에서는 리스트에서 모든 작성자 정보를 다시 또 조회를 해야한다.
- writer user profile 정보를 글 작성시 모두 입력
=> [Refactor] firestore group collection 항목 변경으로 인해 코드 리팩터링하라

src/components/common/Button.test.tsx, src/components/common/Button.tsx, src/components/common/Header.tsx, src/pages/_document.page.tsx, src/styles/GlobalStyles.tsx
- Size: small, medium, large
- color: primary, outlined
- Link와 Button 둘을 추상화하여 공통 컴포넌트로 구현
- hover, disabled, default
- Pretendard 폰트 적용
Outlined, Highlighted
Outlined, Default 
primary, Large
disabled
primary, medium
primary, small 
primary, Highlighted
=> [Feature] 디자인 시스템에 맞춰 버튼 공통 컴포넌트를 구현하라

.eslintrc.js, src/components/common/DropDown.test.tsx, src/components/common/DropDown.tsx, src/components/common/Header.test.tsx, src/components/common/Header.tsx, src/components/common/ProfileImage.tsx, src/components/common/UserNavbar.test.tsx, src/components/common/UserNavbar.tsx, src/containers/common/HeaderContainer.test.tsx
- 로그인 후 헤더 Navbar의 프로필 드롭다운 구현하기
- 드롭다운 메뉴 구현
- 로그아웃, 내정보
=> [Feature] 로그인 후 헤더 Navbar의 프로필 드롭다운 구현하라

src/components/common/Header.tsx, src/components/detail/ApplicantStatusButton.test.tsx, src/components/detail/ApplicantStatusButton.tsx, src/components/detail/CommentView.tsx, src/components/detail/CommentsView.tsx, src/components/detail/DetailContentsSection.tsx, src/components/detail/modal/AskApplyCancelModal.test.tsx, src/components/detail/modal/AskApplyCancelModal.tsx, src/components/home/RecruitPost.tsx, src/components/home/RecruitPosts.tsx, src/components/home/TagsBar.tsx, src/containers/common/HeaderContainer.test.tsx, src/containers/common/HeaderContainer.tsx, src/containers/detail/DetailHeaderContainer.test.tsx, src/styles/GlobalStyles.tsx
- 신청 취소시 신청 취소 모달창 로직을 추가
- memo사용으로 동일한 데이터에 대한  컴포넌트 최적화
- main page의 query가 존재할때 background color가 적용되지 않았던 문제 수정
=> [Feature] 신청 취소시 신청 취소 모달창 로직을 추가하라

src/components/detail/ApplicantStatusButton.test.tsx, src/components/detail/ApplicantStatusButton.tsx, src/components/detail/DetailHeaderSection.test.tsx, src/components/detail/DetailHeaderSection.tsx, src/components/detail/DetailStatusButton.tsx, src/components/home/RecruitPost.tsx, src/containers/detail/DetailHeaderContainer.tsx, src/hooks/useCurrentTime.test.ts, src/hooks/useCurrentTime.ts, src/hooks/useRecruitDateStatus.test.ts, src/hooks/useRecruitDateStatus.ts, src/utils/utils.test.ts, src/utils/utils.ts
- 자동으로 시간초가 변경되는 로직은 모집중일때만
- 모집 마감 및 모집 완료 상태일 때는 detail 페이지에서 글 작성 일자가 나타나고, 모집 중일 때만 ~ 후 모집마감 문구가 나타난다.
- 모집 마감일 경우 신청 및 신청 취소 버튼이 사용자에게 안보여야한다.
=> [Improve] 조건에 따라 디테일 페이지의 버튼 및 날짜 상태가 다르게 나타나게하라

src/components/applicants/ApplicationStatusHeader.test.tsx, src/components/applicants/ApplicationStatusHeader.tsx, src/components/applicants/CompleteApplyFormModal.test.tsx, src/components/applicants/CompleteApplyFormModal.tsx, src/components/common/FormModal.test.tsx, src/components/common/FormModal.tsx, src/components/common/SubHeader.tsx, src/containers/applicants/ApplicationStatusContainer.test.tsx, src/containers/applicants/ApplicationStatusContainer.tsx, src/containers/applicants/ApplicationStatusHeaderContainer.test.tsx, src/containers/applicants/ApplicationStatusHeaderContainer.tsx, src/pages/detail/[id]/applicants.page.tsx, src/pages/detail/[id]/applicants.test.tsx, src/reducers/groupSlice.test.ts, src/reducers/groupSlice.ts, src/services/api/__mocks__/group.ts, src/services/api/group.test.ts, src/services/api/group.ts
1. 작성자는 신청현황 페이지에서 1명 이상의 신청자를 선택 후 모집 완료 버튼을 클릭한다.
2. 모집 완료 모달창이 나타나고 완료하기 버튼을 클릭하면 해당 글 페이지로 redirect되면서 모집을 완료할 수 있다.
3. 팀원 보기 버튼이 나와야 한다.
=> [Feature] 모집 완료 플로우를 구현하라

fixtures/initialStore.ts, src/components/myInfo/RecruitedPost.test.tsx, src/components/myInfo/RecruitedPost.tsx, src/components/myInfo/RecruitedPosts.test.tsx, src/components/myInfo/RecruitedPosts.tsx, src/containers/home/StatusBarContainer.tsx, src/containers/myInfo/RecruitedPostsContainer.test.tsx, src/containers/myInfo/RecruitedPostsContainer.tsx, src/pages/myinfo/recruited.page.tsx, src/pages/myinfo/recruited.test.tsx, src/reducers/myInfoSlice.test.ts, src/reducers/myInfoSlice.ts, src/reducers/rootReducer.test.ts, src/reducers/rootReducer.ts, src/services/api/__mocks__/group.ts, src/services/api/group.test.ts, src/services/api/group.ts, src/utils/utils.test.ts, src/utils/utils.ts
- 내 정보 페이지에서 내가 모집한 팀을 볼 수 있다.
- 해당 팀 클릭시 해당 페이지로 이동
=> [Feature] 내 정보 페이지에서 내가 모집한 팀을 볼 수 있게하라

src/containers/common/HeaderContainer.test.tsx, src/containers/common/HeaderContainer.tsx, src/containers/home/RecruitPostsContainer.test.tsx, src/containers/home/RecruitPostsContainer.tsx
- 로그아웃시 메인 페이지로 이동시킨다.
- 권한이 없는 페이지에서 main으로 redirect된 경우 query를 삭제하여 다시 toast가 뜨지 않게 변경
=> [Fix] 로그아웃시 메인 페이지로 이동시켜라

jest.setup.js, package.json, src/components/home/TagsBar.test.tsx, src/components/home/TagsBar.tsx, src/containers/home/RecruitPostsContainer.test.tsx, src/containers/home/RecruitPostsContainer.tsx, src/containers/home/StatusBarContainer.test.tsx, src/containers/home/StatusBarContainer.tsx, src/hooks/api/useFetchGroups.test.ts, src/hooks/api/useFetchGroups.ts, src/hooks/api/useFetchTagsCount.test.ts, src/hooks/api/useFetchTagsCount.ts, src/pages/_app.page.tsx, src/pages/index.test.tsx, src/recoil/group/atom.ts, src/reducers/groupSlice.test.ts, src/reducers/groupSlice.ts, src/services/api/__mocks__/group.ts, src/services/api/group.test.ts, src/services/api/group.ts, src/services/api/tagsCount.test.ts, src/services/api/tagsCount.ts, src/test/InjectMockProviders.tsx, src/test/InjectTestingRecoilState.tsx, src/test/ReactQueryWrapper.tsx, yarn.lock
1. tagsCount API React Query로 변경
2. getGroups API Ract Query로 변경
3. Main Page의 redux 걷어내기
4. Filter State를 Recoil에 관리
5. Install Recoil, React Query dependencies
=> [Imporve] Main Page에서 호출 중인 API를 React Query를 적용하라

src/hooks/api/auth/useFetchUserProfile.test.ts, src/hooks/api/auth/useFetchUserProfile.ts, src/hooks/api/auth/useSignOut.test.ts, src/hooks/api/auth/useSignOut.ts, src/hooks/api/auth/useSignUp.test.ts, src/hooks/api/auth/useSignUp.ts
- SignOut, SignUp, fetch user profile API를 React Query로 구현
=> [Improve] SignOut, SignUp, fetch user profile API를 React Query로 구현하라

fixtures/alarm.ts, src/components/alarm/AlarmItem.test.tsx, src/components/alarm/AlarmItem.tsx, src/components/alarm/Alarms.test.tsx, src/components/alarm/Alarms.tsx, src/components/common/UserNavbar.tsx, src/containers/alarm/AlarmListContainer.test.tsx, src/containers/alarm/AlarmListContainer.tsx, src/containers/applicants/ApplicationStatusHeaderContainer.test.tsx, src/containers/applicants/ApplicationStatusHeaderContainer.tsx, src/hooks/api/alarm/useFetchAlarms.test.ts, src/hooks/api/alarm/useFetchAlarms.ts, src/hooks/api/group/useUpdateCompletedApply.test.ts, src/hooks/api/group/useUpdateCompletedApply.ts, src/models/alarm.ts, src/pages/alarm.page.tsx, src/pages/alarm.test.tsx, src/services/api/alarm.test.ts, src/services/api/alarm.ts, src/services/api/group.ts, src/utils/firestore.test.ts, src/utils/firestore.ts
- 알람 페이지에서 사용자의 승인, 거절 알람 리스트를 볼 수 있다
- 사용자가 신청한 스터디 및 프로젝트에 대해서 상태가 승인 또는 거절 상태를 알 수 있다.
- 알람 `/alarm` 페이지 생성
- 헤더에 알람 아이콘 추가, 클릭시 알람 페이지로 이동
=> [Feature] 알람 페이지에서 사용자의 승인, 거절 알람 리스트를 볼 수 있게하라

src/components/common/Button.tsx, src/components/detail/ApplicantStatusButton.test.tsx, src/components/detail/ApplicantStatusButton.tsx, src/components/detail/CommentForm.test.tsx, src/components/detail/CommentForm.tsx, src/components/detail/CommentView.test.tsx, src/components/detail/CommentView.tsx, src/components/detail/CommentsView.test.tsx, src/components/detail/CommentsView.tsx, src/containers/detail/CommentsContainer.test.tsx, src/containers/detail/CommentsContainer.tsx, src/hooks/__mocks__/useRenderSuccessToast.ts, src/hooks/api/comment/useDeleteComment.test.ts, src/hooks/api/comment/useDeleteComment.ts, src/hooks/useRenderSuccessToast.test.ts, src/hooks/useRenderSuccessToast.ts
- 댓글 입력 폼을 댓글리스트 상단으로 이동
- 비로그인시 댓글 남기기 버튼 삭제
- 모집 완료 후 팀원도 팀원 보기 가능
- 삭제 시 삭제 confirm 모달창 안띄우기로 변경
- 삭제 시 success toast message 추가
=> [Fix] 디자인 피드백을 반영하라

src/components/common/Core.test.tsx, src/components/common/Core.tsx, src/containers/auth/SignUpContainer.tsx, src/hooks/api/auth/useAuthRedirectResult.test.ts, src/hooks/api/auth/useAuthRedirectResult.ts, src/hooks/api/auth/useCheckSignUp.test.ts, src/hooks/api/auth/useCheckSignUp.ts, src/hooks/api/auth/useSignUp.ts, src/recoil/group/atom.ts, src/services/__mocks__/storage.ts, src/services/api/__mocks__/auth.ts, src/services/api/__mocks__/storage.ts, src/services/api/auth.test.ts, src/services/api/auth.ts, src/services/storage.test.ts, src/services/storage.ts, src/utils/utils.test.ts, src/utils/utils.ts
- "시작하기"(/signup) 페이지로 redirection
- 만약 시작하기 페이지에서 "확인" 버튼을 눌러 가입하지 않았다면 세션 삭제
- 다만, 해당 렌더링된 브라우저인 경우만 세션이 유지되어 "시작하기" 페이지에 접근가능.
- 나머지 경우 firebase auth 세션 삭제
=> [Improve] 처음 로그인하는 사용자에 대한 플로우 수정하라

__mocks__/@remirror/react.js, package.json, src/components/applicants/ApplicantItem.tsx, src/components/detail/DetailContentsSection.tsx, src/components/write/RemirorEditorProvider.tsx, src/components/write/WriteEditor.test.tsx, src/components/write/WriteEditor.tsx, src/styles/StyledToastContainer.ts, src/styles/styledAnchor.ts
- 디테일 페이지의 내용에 각 태그별 CSS 적용 및 이모지 적용
- editor에 twemoji 이모지 추가
- Install svgmoji dependency
=> [Feature] 디테일 페이지의 내용에 각 태그별 CSS 및 이모지를 적용하라

src/components/alarm/AlarmItem.tsx, src/containers/applicants/ApplicationStatusContainer.test.tsx, src/containers/applicants/ApplicationStatusContainer.tsx
- 내 알람의 팀 신청 알람 메시지 클릭시 신청자 페이지로 이동 => 신청 취소한 사용자인 경우 => toast 에러 메시지가 나타난다.
- Error Message: "신청을 취소한 사용자에요."
=> [Improve] 팀 신청 알람 메시지 클릭시 신청 취소한 사용자인 경우 에러 케이스를 추가하라

__mocks__/firebase/auth.js, package.json, src/hooks/api/auth/useAccountWithdrawal.ts, src/hooks/api/auth/useSignOut.ts, src/hooks/api/comment/useAddComment.ts, src/hooks/api/comment/useDeleteComment.test.ts, src/hooks/api/comment/useDeleteComment.ts, src/hooks/api/useCatchAuthErrorWithToast.test.ts, src/hooks/api/useCatchAuthErrorWithToast.ts, yarn.lock
- 무한스크롤적용하면서 react-query key값이 변경되었는데 작성 및 삭제시 react-query key값이 일치하지 않아서 업데이트가 되지 않았음.
- 키 값을 일치시켜 invalidate query를 적용한다.
- 인증 관련 부분 api 실패시 error toast 적용
=> fix: 댓글이 새로고침을 하지 않으면 반영이 안되는 이슈를 수정하라

__mocks__/firebase/auth.js, src/containers/myInfo/MyInfoSettingContainer.test.tsx, src/containers/myInfo/MyInfoSettingContainer.tsx, src/hooks/api/auth/useAccountWithdrawal.test.ts, src/hooks/api/auth/useAccountWithdrawal.ts, src/hooks/api/auth/useReauthenticateWithProvider.test.ts, src/hooks/api/auth/useReauthenticateWithProvider.ts, src/pages/myinfo/setting.test.tsx, src/services/api/__mocks__/auth.ts, src/services/api/auth.test.ts, src/services/api/auth.ts
- 회원탈퇴가 정상적으로 동작하지 않는 이슈 수정
- firebase 회원 탈퇴시 사용자 재인증이 필요하여 탈퇴가 정상적으로 되지 않는 이슈에 재인증 로직을 추가
=> fix: 회원탈퇴가 정상적으로 동작하지 않는 이슈를 수정하라

src/containers/detail/CommentsContainer.tsx, src/hooks/api/comment/queryDataUtils/index.test.ts, src/hooks/api/comment/queryDataUtils/index.ts, src/hooks/api/comment/useAddComment.test.ts, src/hooks/api/comment/useAddComment.ts, src/hooks/api/comment/useDeleteComment.test.ts, src/hooks/api/comment/useDeleteComment.ts, src/services/api/comment.ts
- 댓글이 최신순으로 나타나도록 수정
- 댓글 추가 및 삭제시 refresh 전에는 개수가 변하지 않는 이슈를 수정
- 댓글 추가 및 삭제시 invalidateQueries를 사용하여 api를 호출하는 로직을 setQueryData를 사용하여 api를 호출하지 않고 댓글 상태가 변하도록 수정
=> fix: 댓글이 순서 및 댓글 삭제, 추가시 댓글 개수가 변하지 않는 이슈를 수정하라

src/components/myInfo/MyGroup.test.tsx, src/components/myInfo/MyGroup.tsx, src/components/myInfo/MyGroups.test.tsx, src/components/myInfo/MyGroups.tsx, src/containers/auth/SignUpContainer.test.tsx, src/containers/auth/SignUpContainer.tsx, src/containers/myInfo/AppliedGroupsContainer.test.tsx, src/containers/myInfo/AppliedGroupsContainer.tsx, src/containers/myInfo/MyInfoSettingContainer.test.tsx, src/containers/myInfo/MyInfoSettingContainer.tsx, src/containers/myInfo/RecruitedGroupsContainer.test.tsx, src/containers/myInfo/RecruitedGroupsContainer.tsx, src/hooks/api/group/useInfiniteFetchUserAppliedGroups.ts, src/hooks/api/group/useInfiniteFetchUserRecruitedGroups.ts, src/services/api/alarm.test.ts, src/services/api/alarm.ts, src/services/api/applicants.test.ts, src/services/api/applicants.ts, src/services/api/comment.test.ts, src/services/api/comment.ts, src/services/api/group.test.ts, src/services/api/group.ts, src/utils/__mocks__/firestore.ts, src/utils/firestore.test.ts, src/utils/firestore.ts
- Infinite Scroll이 적용되어있는 리스트부분에서 다음 페이지가 존재하지 않을 경우 다음 페이지 키값이 존재해서 불필요하게 api가 다시 호출되는 이슈
- 처음 infinite scroll api 호출시 첫 페이지가 perPage 보다 작을 경우 발생
- 내 정보 페이지의 신청한 팀, 모집한 팀에서 router.push로 호출하고 있는 부분을 Link로 리팩터링
=> fix: infinite scroll이 적용되어있는 리스트부분에서 불필요한 호출이 발생하는 이슈를 수정하라

src/containers/auth/SignInModalContainer.test.tsx, src/containers/auth/SignInModalContainer.tsx, src/containers/home/RecruitPostsContainer.tsx, src/hooks/useRenderErrorToast.test.ts, src/hooks/useRenderErrorToast.ts, src/pages/detail/[id].page.tsx, src/pages/detail/[id]/applicants.page.tsx, src/pages/detail/[id]/applicants.test.tsx
- 알람에서 모집완료된 글 신청자 리스트 페이지로 이동할 경우
- 신청자 리스트 페이지는 모집이 완료되었으므로 접근할 수 없는 페이지
- 따라서 해당 글로 redirect시킨뒤 "이미 모집이 완료되었어요." 에러 토스트 메시지를 띄우도록 수정
- useRenderErrorToast hook 구현
=> fix: 글이 모집이 완료가 된 글일 때 신청자 리스트로 이동하는 경우 해당 글로 이동하도록 수정하라

__mocks__/firebase-admin.js, src/components/auth/SignUpForm.tsx, src/containers/auth/SignUpContainer.test.tsx, src/containers/auth/SignUpContainer.tsx, src/pages/signup.page.tsx, src/pages/signup.test.tsx, src/services/serverSideProps/authenticatedServerSideProps.test.ts, src/services/serverSideProps/authenticatedServerSideProps.ts
- 회원가입을 하지 않은 사용자, 비로그인인 사용자가 sign up 페이지에 접근했을 때 홈으로 redirected
- 홈으로 redirect시키고 "접근 권한이 없는 페이지에요." 에러 토스트 메시지를 띄운다.
=> feat: 접근 권한이 없는 사용자가 signup 페이지에 접근했을때 홈으로 redirect시키도록 하라

src/components/auth/SignUpForm.test.tsx, src/components/auth/SignUpForm.tsx, src/containers/auth/SignUpContainer.test.tsx
- 시작하기 페이지에서 닉네임 input에 change이벤트가 일어났을때 validate하도록 수정
- 닉네임, 포지션이 입력이 안되어있으면 버튼 disabled
=> fix: sign-up 페이지에서 닉네임이 입력되지 않은 경우 버튼이 disable되도록 수정하라

package.json, src/components/common/SubHeader.tsx, src/components/write/EditorToolbar.test.tsx, src/components/write/EditorToolbar.tsx, src/components/write/WriteEditor.tsx, src/components/write/WriteForm.tsx, src/containers/common/HeaderContainer.test.tsx, src/containers/common/HeaderContainer.tsx, src/containers/write/WriteHeaderContainer.test.tsx, src/containers/write/WriteHeaderContainer.tsx, src/hooks/useActionKeyEvent.test.ts, src/hooks/useActionKeyEvent.ts, src/hooks/useLessThenScrollY.test.ts, src/hooks/useLessThenScrollY.ts, src/hooks/useThrottleCallback.test.ts, src/hooks/useThrottleCallback.ts, src/utils/toast.tsx, yarn.lock
- Sub Header 반응형 적용 및 클릭 이벤트 수정
- 모바일일 때 툴바 컨텐츠가 스크롤이 넘어가는 경우 좌우 shadow 적용
- 글 작성 툴바 반응형 적용
- useActionKeyEvent hook 구현
- useLessThenScrollY hook 구현
- useThrottleCallback hook 구현
- 모바일일 때 타이틀과 editor 툴바를 상단에 고정하도록 구현
- react18 strict mode일 경우 react-responsive가 정상적으로 동작하지 않는 이슈 해결
- update react-responsive dependency (https://github.com/yocontra/react-responsive/pull/294)
=> style: 모바일일 때 글 작성 페이지에서 스크롤 발생할 경우 타이틀과 editor 툴바 상단에 고정하도록 하라

src/components/write/EditorToolbar.test.tsx, src/components/write/EditorToolbar.tsx, src/components/write/TagForm.test.tsx, src/components/write/TagForm.tsx
- 글 작성페이지에 툴바 및 태그 입력 폼 css를 수정
=> fix: 글 작성페이지에 툴바 및 태그 입력 폼 css를 수정하라

src/components/myInfo/ImageSetting.test.tsx, src/components/myInfo/ImageSetting.tsx, src/containers/myInfo/MyInfoSettingContainer.test.tsx, src/containers/myInfo/MyInfoSettingContainer.tsx, src/hooks/api/auth/useUpdateUser.test.ts, src/hooks/api/auth/useUpdateUser.ts, src/services/api/__mocks__/auth.ts
- 내 정보 수정 > 이미지 삭제 클릭시 이미지 삭제 로직 구현
- 이미지가 firebase storage에 저장 중이면 storage에서 삭제 그렇지 않다면 프로필 이미지만 삭제
=> feat: 내 정보 수정 페이지에서 이미지 삭제 클릭시 로직을 추가하라

src/hooks/api/auth/useFetchUserProfile.ts
- react-query v4 변경점을 반영하지 않아서 생긴 이슈
- query.fetchStatus의 fetching중일 때 조건 추가
=> fix: 해더의 사용자 상태에 계속 로딩 스켈레톤이 나타나는 이슈를 수정하라

src/containers/myInfo/MyInfoSettingContainer.test.tsx, src/containers/myInfo/MyInfoSettingContainer.tsx
- 내 정보 수정 페이지에서 이미지가 존재하지 않는 경우 api가 호출되지 않도록 수정
=> fix: 내 정보 수정 페이지에서 이미지가 존재하지 않는 경우 api가 호출되지 않도록 수정하라

src/containers/myInfo/MyInfoSettingContainer.test.tsx, src/containers/myInfo/MyInfoSettingContainer.tsx, src/hooks/api/auth/useUpdateUser.ts
- 이미지 삭제 및 변경 api호출 후 query mutate 상태를 reset시켜줌으로 이전 값을 invalidate시켜주도록 수정
=> fix: 내 정보 수정 페이지의 이미지 삭제 및 수정 시 api가 중복해서 발생하는 이슈를 수정하라

src/components/applicants/ApplicationStatus.test.tsx, src/components/applicants/ApplicationStatus.tsx, src/components/detail/modal/MembersViewModal.tsx, src/containers/applicants/ApplicationStatusContainer.test.tsx, src/containers/applicants/ApplicationStatusContainer.tsx, src/containers/applicants/ApplicationStatusHeaderContainer.tsx, src/containers/detail/DetailContentsContainer.tsx, src/containers/detail/DetailHeaderContainer.tsx, src/hooks/api/applicant/useFetchApplicants.test.ts, src/hooks/api/applicant/useFetchApplicants.ts
- 신청현황 페이지에 suspense concurent mode 적용
- useFetchApplicants api hook suspense를 사용할 수 있도록 리팩터링
=> perf: 신청현황 페이지에 concurrent mode를 적용하라

src/components/write/PublishModalForm.tsx, src/styles/GlobalStyles.tsx
- ios에서 모집 마감일시 datepicker가 width 100%로 나오지 않는 이슈를 수정
=> fix: ios에서 모집 마감일시 datepicker가 width 100%로 나오지 않는 이슈를 수정하라

src/containers/myInfo/AppliedGroupsContainer.test.tsx, src/containers/myInfo/AppliedGroupsContainer.tsx, src/containers/myInfo/RecruitedGroupsContainer.test.tsx, src/containers/myInfo/RecruitedGroupsContainer.tsx, src/hooks/api/auth/useFetchUserProfile.ts, src/hooks/api/auth/useGetUser.ts, src/hooks/api/group/useInfiniteFetchUserAppliedGroups.test.ts, src/hooks/api/group/useInfiniteFetchUserAppliedGroups.ts, src/hooks/api/group/useInfiniteFetchUserRecruitedGroups.test.ts, src/hooks/api/group/useInfiniteFetchUserRecruitedGroups.ts, src/pages/myinfo/applied.page.tsx, src/pages/myinfo/applied.test.tsx, src/pages/myinfo/recruited.page.tsx, src/pages/myinfo/recruited.test.tsx
- 내 정보 페이지의 모집합 팀 및 신청한 팀 리스트에 concurrent mode를 적용
- useFetchProfile과 useGetUser api hook에 suspense 적용
=> refactor: 내 정보 페이지의 모집합 팀 및 신청한 팀 리스트에 concurrent mode를 적용하라

src/hooks/useActionKeyEvent.test.ts, src/hooks/useActionKeyEvent.ts
- 안드로이드 디바이스에서 submit 액션을 막아도 막히지 않는 이슈 수정
- 키 이벤트에서 `event.key`와 `event.code` 두 개를 체크
=> fix: 안드로이드 폰에서 키패드에서 enter클릭시 submit 액션이 발생하는 이슈를 수정하라

src/components/applicants/ApplicationStatus.tsx, src/containers/alarm/AlarmListContainer.tsx, src/containers/applicants/ApplicationStatusContainer.tsx, src/containers/detail/CommentsContainer.tsx, src/containers/myInfo/AppliedGroupsContainer.tsx, src/containers/myInfo/RecruitedGroupsContainer.tsx, src/hooks/api/alarm/useInfiniteFetchAlarms.ts, src/hooks/api/applicant/useFetchApplicants.ts, src/hooks/api/auth/useFetchUserProfile.ts, src/hooks/api/auth/useGetUser.ts, src/hooks/api/comment/useInfiniteFetchComments.ts, src/hooks/api/group/useInfiniteFetchUserAppliedGroups.ts, src/hooks/api/group/useInfiniteFetchUserRecruitedGroups.ts, src/pages/alarm.page.tsx, src/pages/myinfo/applied.page.tsx, src/pages/myinfo/applied.test.tsx, src/pages/myinfo/recruited.page.tsx, src/pages/myinfo/recruited.test.tsx
- 신청자 리스트 페이지에 errorBoundary 적용
- 알람 리스트에 ErrorBoundary 적용
- 글 댓글 리스트에 ErrorBoundary 적용
- 내 신청한 팀 리스트에 errorBoundary 적용
- 사용자 정보를 가져오는 api hook을 ErrorBoundary사용할 수 있게끔 리팩터링
- 내 모집한 팀 리스트에 ErrorBoundary 적용
- useErrorBoundary 옵션이 true인 react-query api hook인 경우 catch error hook 삭제
=> feat(ErrorBoundary): suspense를 사용중인 컴포넌트에 errorBoundary를 적용하라

public/robots.txt, public/sitemap.xml
=> chore(seo): robots 및 sitemap 세팅

src/components/common/FormModal.tsx, src/components/common/Textarea.tsx
- 기존에 사용하던 keyDown이벤트를 useActionKeyEvent hook으로 대체
- FormModal, Textarea
=> refactor: 기존에 사용하던 keyDown이벤트를 useActionKeyEvent hook으로 대체하라

src/components/home/skeleton/TagsBarSkeletonLoader.test.tsx, src/components/home/skeleton/TagsBarSkeletonLoader.tsx, src/containers/home/StatusBarContainer.test.tsx, src/pages/index.test.tsx
- https://github.com/ai/nanoid#react
- nanoid에서 list key props로 사용하지말라고함. 대신에 index를 사용하는게 더 좋다고 함.
=> refactor(TagsBarSkeletonLoader): list item에서 사용중인 nanoid를 삭제하라

src/components/detail/CommentView.test.tsx, src/components/detail/CommentView.tsx, src/components/detail/CommentsView.test.tsx, src/components/detail/CommentsView.tsx, src/components/home/TagsBar.tsx, src/components/myInfo/SettingForm.tsx, src/containers/detail/CommentsContainer.test.tsx, src/containers/detail/CommentsContainer.tsx, src/hooks/api/comment/useDeleteComment.ts
- 상세 페이지의 댓글에 React.memo를 적용하여 성능 최적화
=> perf: 댓글이 보여지는 부분에 memo를 적용하라
